###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
###########################################################
# USE AS ENVIRONMENT VARIABLE
locals {
  AIBOTS_RAG_STATUS_GOVTEXT__SQS = "${data.aws_sqs_queue.aibots_rag-status_govtext.url}"
  AIBOTS_RAG_STATUS_ZIP__SQS = "${data.aws_sqs_queue.aibots_rag-status_zip.url}"
  AIBOTS_RAG_STATUS_MAIN__SQS = "${data.aws_sqs_queue.aibots_rag-status_main.url}"
}

data "aws_sqs_queue" "aibots_rag-status_govtext" {
  name = "${local.sqs_prefix}-${terraform.workspace}ezapp-aibots-rag-status-govtext"
}

data "aws_sqs_queue" "aibots_rag-status_zip" {
  name = "${local.sqs_prefix}-${terraform.workspace}ezapp-aibots-rag-status-zip"
}

data "aws_sqs_queue" "aibots_rag-status_main" {
  name = "${local.sqs_prefix}-${terraform.workspace}ezapp-aibots-rag-status-main"
}

