###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
###########################################################
locals {
  SHAREDSVC_NOUS_API__PTE_URL = "https://nous-api.${local.PTE_URL}"
  SHAREDSVC_NOUS_API__PUB_URL = "https://not_set${local.PUB_URL}"
}

# data "aws_ecr_repository" "sharedsvc-nous-api" {
#   name = "${local.ecr_prefix}-${terraform.workspace}ezapp-sharedsvc-nous-api"
# }
