###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
###########################################################
locals {
  AIBOTS_MAIN_API__PUB_URL = "https://api.${local.PUB_URL}"
  AIBOTS_MAIN_API__PTE_URL = "https://api.${local.PTE_URL}"
  AIBOTS__SECRET = "${data.aws_secretsmanager_secret.aibots-main-api.name}"
  AIBOTS__PARAM = "${data.aws_ssm_parameter.aibots-main-api.name}"

}

data "aws_secretsmanager_secret" "aibots-main-api" {
  name = "${local.secret_prefix}-${terraform.workspace}ezapp-aibots-main-api"
}

data "aws_ssm_parameter" "aibots-main-api" {
  name  = "${local.para_store_prefix}-${terraform.workspace}ezapp-aibots-main-api"
}

# data "aws_ecr_repository" "aibots-main-api" {
#   name = "${local.ecr_prefix}-${terraform.workspace}ezapp-aibots-main-api"
# }
