resource "local_file" "outputdata" {
  filename        = "${path.module}/../data/data.${local.path}.tf"
  file_permission = "0664"
  content         = <<-EOT
###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - $${local.xxx_prefix}                                  #
#  - $${terraform.workspace}                               #
###########################################################
data "aws_networkfirewall_firewall" "${var.project_code}_${var.zone}" {
  name = "$${local.nfw_prefix}-$${terraform.workspace}${var.zone}${var.tier}-${var.project_code}"
}
  EOT
}