###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
#  - ${local.route53_zone_prefix}                         #
###########################################################
################################################################################
# # This part will auto generate the data for the route_tables with a VPC.
################################################################################
data "aws_route_tables" "sharedinfra_ez_all" {
  filter {
    name   = "vpc-id"
    values = [ data.aws_vpc.sharedinfra_ez.id ]
  }
  filter {
    name   = "tag:Terraform"
    values = [ "true" ]
  }
  filter {
    name   = "tag:Environment"
    values = ["${terraform.workspace}"]
  }
}
# output aws_route_tables {
#   value = data.aws_route_tables.sharedinfra_ez_all
# }

locals {
  route_table_ids_sharedinfra_ez = flatten(
    [for index in range( length( data.aws_route_tables.sharedinfra_ez_all.ids ) ) :
      {
        index = index
        route_table_id = data.aws_route_tables.sharedinfra_ez_all.ids[index]
      }
    ]
  )
}
# output flatter_route_table_ids_sharedinfra_ez {
#   value = local.route_table_ids_sharedinfra_ez
# }

data "aws_route_table" "sharedinfra_ez_each" {
  for_each  = { for entry in local.route_table_ids_sharedinfra_ez: "${entry.index}" => entry }
    route_table_id = each.value.route_table_id
}
locals {
  aws_route_table_sharedinfra_ez = distinct(
    flatten(
      [for route_table in data.aws_route_table.sharedinfra_ez_each :
        {
          name = route_table.tags.Name
          route_table_id = route_table.route_table_id
        }
      ]
    )
  )
}
# output flatter_route_table_ids_sharedinfra_ez {
#   value = local.aws_route_table_sharedinfra_ez
# }

data "aws_route_table" "sharedinfra_ez" {
  for_each  = { for entry in local.aws_route_table_sharedinfra_ez: "${entry.name}" => entry }
    route_table_id = each.value.route_table_id
}
