###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
#  - ${local.route53_zone_prefix}                         #
###########################################################
locals{
  default_lambda_runtime = "python3.12"
}

data "aws_lambda_layer_version" "cryptography" {
  layer_name  = "${local.lambda_layer_prefix}-${terraform.workspace}-cryptography"
}

data "aws_lambda_layer_version" "docx-python311" {
  layer_name  = "${local.lambda_layer_prefix}-${terraform.workspace}-docx-python311"
}

data "aws_lambda_layer_version" "jwt-python311" {
  layer_name  = "${local.lambda_layer_prefix}-${terraform.workspace}-jwt-python311"
}

data "aws_lambda_layer_version" "opensearch-py" {
  layer_name  = "${local.lambda_layer_prefix}-${terraform.workspace}-opensearch-py"
}

data "aws_lambda_layer_version" "pillow-python311" {
  layer_name  = "${local.lambda_layer_prefix}-${terraform.workspace}-pillow-python311"
}

data "aws_lambda_layer_version" "pillow" {
  layer_name  = "${local.lambda_layer_prefix}-${terraform.workspace}-pillow"
}

data "aws_lambda_layer_version" "pyjwt" {
  layer_name  = "${local.lambda_layer_prefix}-${terraform.workspace}-pyjwt"
}

data "aws_lambda_layer_version" "pymongo" {
  layer_name  = "${local.lambda_layer_prefix}-${terraform.workspace}-pymongo"
}

data "aws_lambda_layer_version" "python-docx" {
  layer_name  = "${local.lambda_layer_prefix}-${terraform.workspace}-python-docx"
}

data "aws_lambda_layer_version" "requests-aws4auth" {
  layer_name  = "${local.lambda_layer_prefix}-${terraform.workspace}-requests-aws4auth"
}

data "aws_lambda_layer_version" "unstructured-docx" {
  layer_name  = "${local.lambda_layer_prefix}-${terraform.workspace}-unstructured-docx"
}

data "aws_lambda_layer_version" "awswrangler" {
  layer_name = "arn:aws:lambda:ap-southeast-1:336392948345:layer:AWSSDKPandas-Python312"
  version    = 4
}

data "aws_lambda_layer_version" "LambdaInsightsExtension" {
  layer_name  = "arn:aws:lambda:ap-southeast-1:580247275435:layer:LambdaInsightsExtension"
  version    = 53
}
