# output "reminder" {
#   value = <<EOT
#     Remember to configure the API gateway logging to use the IAM.
#   EOT
# }

resource "local_file" "outputdata" {
  filename        = "${path.module}/../data/data.${local.path}.tf"
  file_permission = "0664"
  content         = <<EOT
###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - $${local.xxx_prefix}                                  #
#  - $${terraform.workspace}                               #
###########################################################
# USE AS ENVIRONMENT VARIABLE
locals {
  ${upper( replace(var.project_code, "-", "_") )}_${upper( replace(var.project_desc, "-", "_") )}__PARAM = "$${data.aws_ssm_parameter.${var.project_code}_${var.project_desc}.name}"
}

data "aws_ssm_parameter" "${var.project_code}_${var.project_desc}" {
  name = "$${local.para_store_prefix}-$${terraform.workspace}${var.zone}${var.tier}-${var.project_code}-${var.project_desc}"
}
EOT
}