###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
#  - ${local.route53_zone_prefix}                         #
###########################################################
data "aws_wafv2_web_acl" "sharedinfra_ez_regional" {
  name  = "${local.waf_prefix}-${terraform.workspace}ezingress-sharedinfra-regional"
  scope = "REGIONAL"
}

data "aws_wafv2_web_acl" "sharedinfra_ez_cloudfront" {
  provider = aws.east
  name  = "${local.waf_prefix}-${terraform.workspace}ezingress-sharedinfra-cloudfront"
  scope = "CLOUDFRONT"
}

########################################################################
########################################################################
provider "aws" {
  alias  = "east"
  region = "us-east-1"
}
