output "REMINDER" {
  value = <<-EOT
    This is the DNS CNAME to use in ITSM
    ${module.private_alb.lb.dns_name}
  EOT
}

resource "local_file" "outputdata" {
  filename        = "${path.module}/../data/data.${local.path}.tf"
  file_permission = "0664"
  content         = <<-EOT
###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - $${local.xxx_prefix}                                  #
#  - $${terraform.workspace}                               #
#  - $${local.route53_zone_prefix}                         #
###########################################################
data "aws_lb" "${var.zone}${var.tier}${local.alb_prefix}_pte" {
  tags = {
    "Project-Code" = "${var.project_code}"
    "Environment" = "$${terraform.workspace}"
    "Terraform" = "true"
    "Tier" = "${var.tier}"
    "Zone" = "${var.zone}"
    "type" = "$${local.alb_prefix}"
    "scheme" = "private"
  }
}

data "aws_lb_listener" "${var.zone}${var.tier}${local.alb_prefix}_pte_443" {
  load_balancer_arn = data.aws_lb.${var.zone}${var.tier}${local.alb_prefix}_pte.arn
  port              = 443
}

data "aws_security_group" "${var.zone}${var.tier}${local.alb_prefix}_sso" {
  filter {
    name     = "tag:Terraform"
    values = ["true"]
  }
  filter {
    name     = "tag:Environment"
    values = ["$${terraform.workspace}"]
  }
  filter {
    name     = "tag:Project-Code"
    values = ["${var.project_code}"]
  }
  filter {
    name     = "tag:Project-Desc"
    values = ["${var.project_desc}-sso"]
  }
  filter {
    name     = "tag:Zone"
    values = ["${var.zone}"]
  }
  filter {
    name     = "tag:Tier"
    values = ["${var.tier}"]
  }
}
  EOT
}