# output "reminder" {
#   value = <<EOT
#     Remember to configure the API gateway logging to use the IAM.
#   EOT
# }

resource "local_file" "outputdata" {
  filename        = "${path.module}/../data/data.${local.path}.tf"
  file_permission = "0664"
  content         = <<EOT
###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - $${local.xxx_prefix}                                  #
#  - $${terraform.workspace}                               #
#  - $${local.route53_zone_prefix}                         #
###########################################################
data "aws_s3_bucket" "${var.project_code}" {
  bucket = "${local.s3_prefix}-$${terraform.workspace}${var.zone}${var.tier}-${var.project_code}-$${data.aws_caller_identity.current.account_id}-${var.project_desc}"
}

# USE AS ENVIRONMENT VARIABLE
locals{
  ${upper(var.project_code)}_${upper(var.project_desc)}__BUCKET = "$${data.aws_s3_bucket.${var.project_code}.id}"

  # # this is where the batch xlsx are dropped
  # ${upper(var.project_code)}_BATCH__PATH = "batch/"

  # # this is where the batch xlsx are dropped
  # ${upper(var.project_code)}_BATCH_UPLOAD__PATH = "$${local.${upper(var.project_code)}_BATCH__PATH}upload/"
  # ${upper(var.project_code)}_BATCH_UPLOAD__FILE_EXT = ".xlsx" # this is the trigger to batch genappr lambda
  
  # # this is where the generated appr are dropped
  # ${upper(var.project_code)}_BATCH_GEN_APPR__PATH = "$${local.${upper(var.project_code)}_BATCH__PATH}upload/"
  # ${upper(var.project_code)}_BATCH_GEN_APPR__FILE_EXT = ".docx" # place holder, not used at the moment.

  # # this is where the zipped appr are dropped
  # ${upper(var.project_code)}_BATCH_ZIPPED_APPR__PATH = "$${local.${upper(var.project_code)}_BATCH__PATH}zipped_appr/"
  # ${upper(var.project_code)}_BATCH_ZIPPED_APPR__FILE_EXT = ".xlsx" # this is not used at the moment, using cloudwatch schedule

  # # this is where the sent job gets archived
  # ${upper(var.project_code)}_BATCH_ARCHIVE__PATH = "$${local.${upper(var.project_code)}_BATCH__PATH}archive/"
  # ${upper(var.project_code)}_BATCH_ARCHIVE__FILE_EXT = ".zip" # this is the trigger to ses
}
EOT
}