###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
#  - ${local.route53_zone_prefix}                         #
###########################################################

data "aws_s3_bucket" "athena" {
  bucket = "${local.s3_prefix}-${terraform.workspace}ez-sharedinfra-${data.aws_caller_identity.current.account_id}-athena"
}

data "aws_s3_bucket" "cost-usage-reports" {
  bucket = "${local.s3_prefix}-${terraform.workspace}ez-sharedinfra-${data.aws_caller_identity.current.account_id}-cost-usage-reports"
}

data "aws_s3_bucket" "access-logs-elb" {
  bucket = "${local.s3_prefix}-${terraform.workspace}ez-sharedinfra-${data.aws_caller_identity.current.account_id}-access-logs-elb"
}

data "aws_s3_bucket" "access-logs-cloudfront" {
  bucket = "${local.s3_prefix}-${terraform.workspace}ez-sharedinfra-${data.aws_caller_identity.current.account_id}-access-logs-cloudfront"
}

