###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
#  - ${local.route53_zone_prefix}                         #
###########################################################
data "aws_s3_bucket" "access-logs-s3" {
  bucket = "${local.s3_prefix}-${terraform.workspace}ez-sharedinfra-${data.aws_caller_identity.current.account_id}-access-logs-s3"
}
