resource "local_file" "outputdata" {
  filename        = "${path.module}/../data/data.${local.path}.tf"
  file_permission = "0664"
  content         = <<EOT
###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - $${local.xxx_prefix}                                  #
#  - $${terraform.workspace}                               #
#  - $${local.route53_zone_prefix}                         #
###########################################################
data "aws_s3_bucket" "${var.project_code}_${var.project_desc}" {
  bucket = "${local.s3_prefix}-$${terraform.workspace}${var.zone}${var.tier}-${var.project_code}-$${data.aws_caller_identity.current.account_id}-${var.project_desc}"
}

data "aws_secretsmanager_secret" "${var.project_code}_${var.project_desc}" {
  name = "$${local.secret_prefix}-$${terraform.workspace}${var.zone}${var.tier}-${var.project_code}-${var.project_desc}"
}

data "aws_ssm_parameter" "${var.project_code}_${var.project_desc}" {
  name = "$${local.para_store_prefix}-$${terraform.workspace}${var.zone}${var.tier}-${var.project_code}-${var.project_desc}-publickey"
}

# USE AS ENVIRONMENT VARIABLE
locals {
  ${upper( replace(var.project_code, "-", "_") )}_${upper( replace(var.project_desc, "-", "_") )}__PUB_URL = "https://public.$${local.route53_zone_prefix}${var.domain}"
  ${upper( replace(var.project_code, "-", "_") )}_${upper( replace(var.project_desc, "-", "_") )}__BUCKET = "$${data.aws_s3_bucket.${var.project_code}_${var.project_desc}.id}"
  ${upper( replace(var.project_code, "-", "_") )}_${upper( replace(var.project_desc, "-", "_") )}__SECRET = "$${data.aws_secretsmanager_secret.${var.project_code}_${var.project_desc}.name}"
  ${upper( replace(var.project_code, "-", "_") )}_${upper( replace(var.project_desc, "-", "_") )}__PARAM = "$${data.aws_ssm_parameter.${var.project_code}_${var.project_desc}.name}"
}
EOT
}

output fqdn {
  value = aws_cloudfront_distribution.project.aliases
}