###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
#  - ${local.route53_zone_prefix}                         #
###########################################################
data "aws_lambda_function" "ecs_stop_task" {
  function_name = "${local.lambda_prefix}-${terraform.workspace}ez-sharedinfra-ecs-stop-task"
}
