###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
#  - ${local.route53_zone_prefix}                         #
###########################################################
data "aws_lb" "ezingressnlb_pub" {
  tags = {
    "Project-Code" = "sharedinfra"
    "Environment" = "${terraform.workspace}"
    "Terraform" = "true"
    "Tier" = "ingress"
    "Zone" = "ez"
    "type" = "${local.alb_prefix}"
    "scheme" = "public"
  }
}

data "aws_lb_listener" "ezingressnlb_pub_443" {
  load_balancer_arn = data.aws_lb.ezingressalb_pub.arn
  port              = 443
}

data "aws_security_group" "ezingressnlb_pub" {
  filter {
    name     = "tag:Terraform"
    values = ["true"]
  }
  filter {
    name     = "tag:Environment"
    values = ["${terraform.workspace}"]
  }
  filter {
    name     = "tag:Project-Code"
    values = ["sharedinfra"]
  }
  filter {
    name     = "tag:Project-Desc"
    values = ["ingress"]
  }
  filter {
    name     = "tag:Zone"
    values = ["ez"]
  }
  filter {
    name     = "tag:Tier"
    values = ["ingress"]
  }
}
