###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
#  - ${local.route53_zone_prefix}                         #
###########################################################
################################################################################
# # nacl is different from subnets route_tables and security_groups
# # nacl does not have a data.aws_network_acl
# # it only has nacl.aws_network_acls (note the S) which only return a list of nacl_ids
# # the typical auto gen with vpc_id will not work.
################################################################################
# USE AS ENVIRONMENT VARIABLE
locals {
  SHAREDINFRA__SECRET = "${data.aws_secretsmanager_secrets.sharedinfra-secret.name}"
}

data "aws_secretsmanager_secrets" "sharedinfra-secret" {
  filter {
    name   = "tag:Terraform"
    values = ["true"]
  }
  filter {
    name   = "tag:Environment"
    values = ["${terraform.workspace}"]
  }
  filter {
    name   = "tag:Project-Code"
    values = ["sharedinfra"]
  }
  filter {
    name   = "tag:Project-Desc"
    values = [""]
  }
  filter {
    name   = "tag:Zone"
    values = ["ez"]
  }
}
