###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
#  - ${local.route53_zone_prefix}                         #
###########################################################
data "terraform_remote_state" "sharedinfra_endpt" {
  backend = "s3"
  config = {
    bucket = "${local.s3_prefix}-gvt-gdp-${data.aws_caller_identity.current.account_id}-terraform-statefile"
    key    = "env:/${terraform.workspace}/0012-sharedinfra-endpt/terraform.tfstate"
    region = data.aws_region.current.name
  }
}

locals {
  all_endpoints = [ "bedrock-runtime.ap-southeast-1.amazonaws.com", "api.ecr.ap-southeast-1.amazonaws.com", "dkr.ecr.ap-southeast-1.amazonaws.com", "ecs.ap-southeast-1.amazonaws.com", "logs.ap-southeast-1.amazonaws.com", "secretsmanager.ap-southeast-1.amazonaws.com", "sqs.ap-southeast-1.amazonaws.com", "ssm.ap-southeast-1.amazonaws.com", ]
}

data "aws_vpc_endpoint" "logs" {
  filter {
    name   = "tag:Name"
    values = ["${local.vpce_prefix}-${terraform.workspace}ezendpt-sharedinfra-com.amazonaws.ap-southeast-1.logs"]
  }
}

data "aws_vpc_endpoint" "secretsmanager" {
  filter {
    name   = "tag:Name"
    values = ["${local.vpce_prefix}-${terraform.workspace}ezendpt-sharedinfra-com.amazonaws.ap-southeast-1.secretsmanager"]
  }
}

data "aws_vpc_endpoint" "ecr_api" {
  filter {
    name   = "tag:Name"
    values = ["${local.vpce_prefix}-${terraform.workspace}ezendpt-sharedinfra-com.amazonaws.ap-southeast-1.ecr.api"]
  }
}

data "aws_vpc_endpoint" "ecr_dkr" {
  filter {
    name   = "tag:Name"
    values = ["${local.vpce_prefix}-${terraform.workspace}ezendpt-sharedinfra-com.amazonaws.ap-southeast-1.ecr.dkr"]
  }
}

data "aws_vpc_endpoint" "ecs" {
  filter {
    name   = "tag:Name"
    values = ["${local.vpce_prefix}-${terraform.workspace}ezendpt-sharedinfra-com.amazonaws.ap-southeast-1.ecs"]
  }
}

data "aws_vpc_endpoint" "sqs" {
  filter {
    name   = "tag:Name"
    values = ["${local.vpce_prefix}-${terraform.workspace}ezendpt-sharedinfra-com.amazonaws.ap-southeast-1.sqs"]
  }
}

data "aws_vpc_endpoint" "ssm" {
  filter {
    name   = "tag:Name"
    values = ["${local.vpce_prefix}-${terraform.workspace}ezendpt-sharedinfra-com.amazonaws.ap-southeast-1.ssm"]
  }
}

data "aws_vpc_endpoint" "bedrock-runtime" {
  filter {
    name   = "tag:Name"
    values = ["${local.vpce_prefix}-${terraform.workspace}ezendpt-sharedinfra-com.amazonaws.ap-southeast-1.bedrock-runtime"]
  }
}

