###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
#  - ${local.route53_zone_prefix}                         #
###########################################################
# USE AS ENVIRONMENT VARIABLE
locals {
  AIBOTS_API_REDIS__PARAM = "${data.aws_ssm_parameter.aibots_api-redis.name}"
}

data "aws_ssm_parameter" "aibots_api-redis" {
  name  = "${local.para_store_prefix}-${terraform.workspace}ezdb-aibots-api-redis"
}

data "aws_security_group" "aibots_api-redis" {
  name  = "${local.secgrp_prefix}-${terraform.workspace}ezdb-aibots-api-redis"
}
