###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
#  - ${local.route53_zone_prefix}                         #
###########################################################
data "aws_cognito_user_pools" "wog-aad" {
  name  = "${local.cognito_prefix}-${terraform.workspace}ez-sharedinfra-sso"
}

locals {
  # resource "cognito_user_pool_domain"
  # >> domain
  # Terraform does not have a data for this.
  # This is the FQDN that you provide when you onboard to WOG AAD.
  cognito_user_pool_domain_wog-aad = "${terraform.workspace}-sso-gdp"
  
  # resource "aws_cognito_identity_provider"
  # This is the the name of aws_cognito_identity_provider.
  # Terraform does not have a data for this.
  # this is remarked here because IaC name it using aws_cognito_user_pools.wog-aad.name
  # you can unremark in you standalone setup.
  # cognito_identity_providers_wog-aad = data.aws_cognito_user_pools.wog-aad.name
}
