###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
#  - ${local.route53_zone_prefix}                         #
###########################################################
################################################################################
# # This part will auto generate the data for the security_groups with a VPC.
################################################################################
data "aws_security_groups" "sharedsvc_ez_all" {
  filter {
    name   = "vpc-id"
    values = [ data.aws_vpc.sharedsvc_ez.id ]
  }
  filter {
    name   = "tag:Terraform"
    values = [ "true" ]
  }
  filter {
    name   = "tag:Environment"
    values = ["${terraform.workspace}"]
  }
}
# output aws_security_groups_all_ids {
#   value = data.aws_security_groups.sharedsvc_ez_all.ids
# }

locals {
  security_group_ids_sharedsvc_ez = flatten(
    [for index in range( length( data.aws_security_groups.sharedsvc_ez_all.ids ) ) :
      {
        index = index
        id = data.aws_security_groups.sharedsvc_ez_all.ids[index]
      }
    ]
  )
}
# output flatter_security_group_ids {
#   value = local.security_group_ids_sharedsvc_ez
# }

data "aws_security_group" "sharedsvc_ez_each" {
  for_each  = { for entry in local.security_group_ids_sharedsvc_ez: "${entry.index}" => entry }
    id = each.value.id
}
locals {
  aws_security_group_sharedsvc_ez_each = distinct(
    flatten(
      [for security_group in data.aws_security_group.sharedsvc_ez_each :
        {
          name = security_group.tags.Name
          id = security_group.id
        }
      ]
    )
  )
}
# output flatter_security_group_ids {
#   value = local.aws_security_group_sharedsvc_ez_each
# }

data "aws_security_group" "sharedsvc_ez" {
  for_each  = { for entry in local.aws_security_group_sharedsvc_ez_each: "${entry.name}" => entry }
    id = each.value.id
}
