###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
#  - ${local.route53_zone_prefix}                         #
###########################################################
################################################################################
# # nacl is different from subnets route_tables and security_groups
# # nacl does not have a data.aws_network_acl
# # it only has nacl.aws_network_acls (note the S) which only return a list of nacl_ids
# # the typical auto gen with vpc_id will not work.
################################################################################
data "aws_network_acls" "management_ez_all" {
  filter {
    name   = "tag:Terraform"
    values = ["true"]
  }
  filter {
    name   = "tag:Environment"
    values = ["${terraform.workspace}"]
  }
  filter {
    name   = "tag:Project-Code"
    values = ["management"]
  }
  filter {
    name   = "tag:Zone"
    values = ["ez"]
  }
}

data "aws_network_acls" "management_ez_cicd" {
  filter {
    name   = "tag:Terraform"
    values = ["true"]
  }
  filter {
    name   = "tag:Environment"
    values = ["${terraform.workspace}"]
  }
  filter {
    name   = "tag:Project-Code"
    values = ["management"]
  }
  filter {
    name   = "tag:Zone"
    values = ["ez"]
  }
  filter {
    name   = "tag:Tier"
    values = ["cicd"]
  }
}

data "aws_network_acls" "management_ez_test" {
  filter {
    name   = "tag:Terraform"
    values = ["true"]
  }
  filter {
    name   = "tag:Environment"
    values = ["${terraform.workspace}"]
  }
  filter {
    name   = "tag:Project-Code"
    values = ["management"]
  }
  filter {
    name   = "tag:Zone"
    values = ["ez"]
  }
  filter {
    name   = "tag:Tier"
    values = ["test"]
  }
}

data "aws_network_acls" "management_ez_tgw" {
  filter {
    name   = "tag:Terraform"
    values = ["true"]
  }
  filter {
    name   = "tag:Environment"
    values = ["${terraform.workspace}"]
  }
  filter {
    name   = "tag:Project-Code"
    values = ["management"]
  }
  filter {
    name   = "tag:Zone"
    values = ["ez"]
  }
  filter {
    name   = "tag:Tier"
    values = ["tgw"]
  }
}

