###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
###########################################################
locals {
  AIBOTS_MAIN_WEB__PUB_URL = "https://${local.PUB_URL}"
  AIBOTS_MAIN_WEB__PTE_URL = "https://not_set${local.PTE_URL}"
  AIBOTS__SECRET = "${data.aws_secretsmanager_secret.aibots-main-web.name}"
}

data "aws_secretsmanager_secret" "aibots-main-web" {
  name = "${local.secret_prefix}-${terraform.workspace}ezapp-aibots-main-web"
}

# data "aws_ecr_repository" "aibots-main-web" {
#   name = "${local.ecr_prefix}-${terraform.workspace}ezapp-aibots-main-web"
# }
