###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
#  - ${local.route53_zone_prefix}                         #
###########################################################
# USE AS ENVIRONMENT VARIABLE
locals {
  SHAREDSVC_DB__SECRET = "${data.aws_secretsmanager_secret.sharedsvc_main.name}"
}

data "aws_secretsmanager_secret" "sharedsvc_main" {
  name = "${local.secret_prefix}-${terraform.workspace}ezdb-sharedsvc-main"
}
