###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
#  - ${local.route53_zone_prefix}                         #
###########################################################
data "aws_nat_gateway" "sharedinfra_ez" {
  vpc_id = data.aws_vpc.sharedinfra_ez.id
  state = "available"
}
