###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
###########################################################
data "aws_networkfirewall_firewall" "sharedinfra_ez" {
  name = "${local.nfw_prefix}-${terraform.workspace}ezinspect-sharedinfra"
}
