###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
###########################################################

data "aws_lambda_function" "sharedsvc-scheduler-ingest" {
  function_name = "${local.lambda_prefix}-${terraform.workspace}ezapp-sharedsvc-scheduler-02-ingest"
}

data "aws_sqs_queues" "sharedsvc-scheduler-sqs" {
  queue_name_prefix = "${local.sqs_prefix}-${terraform.workspace}ezapp-sharedsvc-scheduler-03-fanout"
}

data "aws_sqs_queues" "sharedsvc-scheduler-sqs-dlq" {
  queue_name_prefix = "${local.sqs_prefix}-${terraform.workspace}ezapp-sharedsvc-scheduler-03-fanout-dlq"
}

data "aws_lambda_function" "sharedsvc-scheduler-process" {
  function_name = "${local.lambda_prefix}-${terraform.workspace}ezapp-sharedsvc-scheduler-04-zipappr"
}
