# locals {
#   route53_zone_name = "aws_route53_zone.hosted_zone.name"
# }

# locals {
#   route53_zone_name = flatten(
#     [for r53zone in var.route53_zone_name :
#       {
#         data_name     = replace( "${r53zone}", ".", "_")
#         resource_name = "${local.route53_zone_prefix}${r53zone}"
#       }
#     ]
#   )
# }

resource "local_file" "outputdata" {
  filename        = "${path.module}/../data/data.${local.path}.tf"
  file_permission = "0664"
  content         = <<-EOT
###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - $${local.xxx_prefix}                                  #
#  - $${terraform.workspace}                               #
#  - $${local.route53_zone_prefix}                         #
###########################################################
# USE AS ENVIRONMENT VARIABLE
locals {
  PUB_URL = "$${data.aws_route53_zone.${replace(var.hosted_zone_name, ".", "_")}.name}"
  PTE_URL = "${var.record}.$${data.aws_route53_zone.${replace(var.hosted_zone_name, ".", "_")}.name}"
}

data "aws_route53_zone" "${replace(var.hosted_zone_name, ".", "_")}" {
  name         = "$${local.route53_zone_prefix}${var.hosted_zone_name}"
  private_zone = true
}
  EOT
}