resource "local_file" "outputdata" {
  filename        = "${path.module}/../data/data.${local.path}.tf"
  file_permission = "0664"
  content         = <<-EOT
###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - $${local.xxx_prefix}                                  #
#  - $${terraform.workspace}                               #
#  - $${local.route53_zone_prefix}                         #
###########################################################
data "aws_wafv2_web_acl" "${var.project_code}_${var.zone}_regional" {
  name  = "$${local.waf_prefix}-$${terraform.workspace}${var.zone}${var.tier}-${var.project_code}-regional"
  scope = "REGIONAL"
}

data "aws_wafv2_web_acl" "${var.project_code}_${var.zone}_cloudfront" {
  provider = aws.east
  name  = "$${local.waf_prefix}-$${terraform.workspace}${var.zone}${var.tier}-${var.project_code}-cloudfront"
  scope = "CLOUDFRONT"
}

########################################################################
########################################################################
provider "aws" {
  alias  = "east"
  region = "us-east-1"
}
  EOT
}