###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
#  - ${local.route53_zone_prefix}                         #
###########################################################
data "aws_s3_bucket" "aibots" {
  bucket = "s3-${terraform.workspace}ezapp-aibots-${data.aws_caller_identity.current.account_id}-project"
}

# USE AS ENVIRONMENT VARIABLE
locals{
  AIBOTS_PROJECT__BUCKET = "${data.aws_s3_bucket.aibots.id}"

  # # this is where the batch xlsx are dropped
  # AIBOTS_BATCH__PATH = "batch/"

  # # this is where the batch xlsx are dropped
  # AIBOTS_BATCH_UPLOAD__PATH = "${local.AIBOTS_BATCH__PATH}upload/"
  # AIBOTS_BATCH_UPLOAD__FILE_EXT = ".xlsx" # this is the trigger to batch genappr lambda
  
  # # this is where the generated appr are dropped
  # AIBOTS_BATCH_GEN_APPR__PATH = "${local.AIBOTS_BATCH__PATH}upload/"
  # AIBOTS_BATCH_GEN_APPR__FILE_EXT = ".docx" # place holder, not used at the moment.

  # # this is where the zipped appr are dropped
  # AIBOTS_BATCH_ZIPPED_APPR__PATH = "${local.AIBOTS_BATCH__PATH}zipped_appr/"
  # AIBOTS_BATCH_ZIPPED_APPR__FILE_EXT = ".xlsx" # this is not used at the moment, using cloudwatch schedule

  # # this is where the sent job gets archived
  # AIBOTS_BATCH_ARCHIVE__PATH = "${local.AIBOTS_BATCH__PATH}archive/"
  # AIBOTS_BATCH_ARCHIVE__FILE_EXT = ".zip" # this is the trigger to ses
}
