###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
###########################################################
# USE AS ENVIRONMENT VARIABLE
locals {
  AIBOTS_RAG_EXTSTACK_ZIP__SQS = "${data.aws_sqs_queue.aibots_rag-extstack_zip.url}"
  AIBOTS_RAG_EXTSTACK_GOVTEXT__SQS = "${data.aws_sqs_queue.aibots_rag-extstack_govtext.url}"
}

data "aws_sqs_queue" "aibots_rag-extstack_zip" {
  name = "${local.sqs_prefix}-${terraform.workspace}ezapp-aibots-rag-extstack-zip"
}

data "aws_sqs_queue" "aibots_rag-extstack_govtext" {
  name = "${local.sqs_prefix}-${terraform.workspace}ezapp-aibots-rag-extstack-govtext"
}

