# output "reminder" {
#   value = <<EOT
#     Remember to configure the API gateway logging to use the IAM.
#   EOT
# }

resource "local_file" "outputdata" {
  filename        = "${path.module}/../data/data.${local.path}.tf"
  file_permission = "0664"
  content         = <<EOT
###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - $${local.xxx_prefix}                                  #
#  - $${terraform.workspace}                               #
###########################################################
# USE AS ENVIRONMENT VARIABLE
locals {
%{for process in var.process~}
  ${replace(upper(var.project_code), "-", "_" )}_${replace(upper(var.project_desc), "-", "_" )}_${replace(upper(process.name), "-", "_" )}__SQS = "$${data.aws_sqs_queue.${var.project_code}_${var.project_desc}_${process.name}.url}"
%{endfor~}
}

%{for process in var.process~}
data "aws_sqs_queue" "${var.project_code}_${var.project_desc}_${process.name}" {
  name = "$${local.sqs_prefix}-$${terraform.workspace}${var.zone}${var.tier}-${var.project_code}-${var.project_desc}-${process.name}"
}

%{endfor~}
EOT
}