resource "local_file" "outputdata" {
  filename        = "${path.module}/../data/data.${local.path}.tf"
  file_permission = "0664"
  content         = <<EOT
###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - $${local.xxx_prefix}                                  #
#  - $${terraform.workspace}                               #
#  - $${local.route53_zone_prefix}                         #
###########################################################

# USE AS ENVIRONMENT VARIABLE
locals {
  ${upper( replace(var.project_code, "-", "_") )}_EMAIL_SMTP__${upper(local.secret_prefix)} = "$${data.aws_secretsmanager_secret.${var.project_code}-${var.project_desc}-${var.from}.name}"
}

data "aws_secretsmanager_secret" "${var.project_code}-${var.project_desc}-${var.from}" {
  name = "$${local.secret_prefix}-$${terraform.workspace}${var.zone}${var.tier}-${var.project_code}-${var.project_desc}-${var.from}"
}

EOT
}