output "REMINDER" {
  value = <<EOT
  You need to run 9990-private_host_zone to create R53 records if you are sharing the endpoints.
  
  If you are removing endpoints, you have to clickops and remove the A Records from the Private Hosted Zone,
  then run this project follow by 9990-private_host_zone.
  EOT
}

locals {
  endpoints = flatten(
    [for endpoint in module.interface_endpoints.aws_vpc_endpoints_list :
      {
        # data_name     = replace( endpoint.service_name, "com.amazonaws.${data.aws_region.current.name}.", "")
        # resource_name = replace( replace( endpoint.service_name, "com.amazonaws.${data.aws_region.current.name}.", ""), ".", "_")
        data_name     = replace(endpoint.tags.Name, local.vpce_name, "")
        resource_name = replace( replace( replace(endpoint.tags.Name, local.vpce_name, ""), "com.amazonaws.${data.aws_region.current.name}.", "" ), ".", "_")
      }
    ]
  )
}

# all_endpoints = [ %{for endpoint in var.endpoints~} "${endpoint}", %{endfor~} ]
resource "local_file" "outputdata" {
  filename        = "${path.module}/../data/data.${local.path}.tf"
  file_permission = "0664"
  content         = <<-EOT
###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - $${local.xxx_prefix}                                  #
#  - $${terraform.workspace}                               #
#  - $${local.route53_zone_prefix}                         #
###########################################################
data "terraform_remote_state" "${var.project_code}_endpt" {
  backend = "s3"
  config = {
    bucket = "$${local.s3_prefix}-${var.agency_code}-${var.dept}-$${data.aws_caller_identity.current.account_id}-terraform-statefile"
    key    = "env:/$${terraform.workspace}/${local.path}/terraform.tfstate"
    region = data.aws_region.current.name
  }
}

locals {
  all_endpoints = [ %{for endpoint in module.interface_endpoints.aws_route53_zones_list ~} "${endpoint.name}", %{endfor~} ]
}

%{for endpoint in var.interface_endpts~}
data "aws_vpc_endpoint" "${replace( replace( replace( endpoint.name == null ? endpoint.service_name : endpoint.name , local.vpce_name, ""), "com.amazonaws.${data.aws_region.current.name}.", "" ), ".", "_")}" {
  filter {
    name   = "tag:Name"
    values = ["$${local.vpce_prefix}-$${terraform.workspace}${var.zone}${var.tier}-${var.project_code}-${endpoint.name == null ? endpoint.service_name : endpoint.name}"]
  }
}

%{endfor~}
  EOT
}

output all_endpoints{
  # value = module.interface_endpoints.aws_route53_zones_list.*.name
  value = [
    for aws_route53_zones in module.interface_endpoints.aws_route53_zones_list : aws_route53_zones.name
  ]
}

# %{for endpoint in var.interface_endpts~}
# data "aws_vpc_endpoint" "${replace( replace( replace( try(endpoint.name, endpoint.service_name), local.vpce_name, ""), "com.amazonaws.${data.aws_region.current.name}.", "" ), ".", "_")}" {
#   filter {
#     name   = "tag:Name"
#     values = ["$${local.vpce_prefix}-$${terraform.workspace}${var.zone}${var.tier}-${var.project_code}-${try(endpoint.name, endpoint.service_name)}"]
#   }
# }

# %{endfor~}
