###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
#  - ${local.route53_zone_prefix}                         #
###########################################################
data "aws_ec2_transit_gateway" "sharedinfra_ez" {
  filter {
    name     = "tag:Terraform"
    values = ["true"]
  }
  filter {
    name     = "tag:Environment"
    values = ["${terraform.workspace}"]
  }
  filter {
    name     = "tag:Project-Code"
    values = ["sharedinfra"]
  }
  filter {
    name     = "tag:Zone"
    values = ["ez"]
  }
}
