# output "reminder" {
#   value = <<EOT
#     Remember to configure the API gateway logging to use the IAM.
#   EOT
# }

resource "local_file" "outputdata" {
  filename        = "${path.module}/../data/data.${local.path}.tf"
  file_permission = "0664"
  content         = <<EOT
###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - $${local.xxx_prefix}                                  #
#  - $${terraform.workspace}                               #
###########################################################
%{for process in var.process~}
data "aws_lambda_function" "${var.project_code}-${var.project_desc}-${process.name}" {
  function_name = "$${local.lambda_prefix}-$${terraform.workspace}${var.zone}${var.tier}-${var.project_code}-${var.project_desc}-${process.name}"
}

data "aws_sqs_queue" "${var.project_code}-${var.project_desc}-${process.name}" {
  name = "$${local.sqs_prefix}-$${terraform.workspace}${var.zone}${var.tier}-${var.project_code}-${var.project_desc}-${process.name}"
}

%{endfor~}
EOT
}