###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
#  - ${local.route53_zone_prefix}                         #
###########################################################
################################################################################
# # This part will auto generate the data for the subnets with a VPC.
################################################################################
data "aws_subnets" "sharedsvc_ez_all" {
  filter {
    name   = "vpc-id"
    values = [ data.aws_vpc.sharedsvc_ez.id ]
  }
  filter {
    name   = "tag:Terraform"
    values = [ "true" ]
  }
  filter {
    name   = "tag:Environment"
    values = ["${terraform.workspace}"]
  }
}
# output aws_subnets_sharedsvc_ez_all_ids {
#   value = data.aws_subnets.sharedsvc_ez_all.ids
# }

locals {
  subnet_ids_sharedsvc_ez = flatten(
    [for index in range( length( data.aws_subnets.sharedsvc_ez_all.ids ) ) :
      {
        index = index
        id = data.aws_subnets.sharedsvc_ez_all.ids[index]
      }
    ]
  )
}
# output flatter_subnet_ids_sharedsvc_ez {
#   value = local.subnet_ids_sharedsvc_ez
# }

data "aws_subnet" "sharedsvc_ez_each" {
  for_each  = { for entry in local.subnet_ids_sharedsvc_ez: "${entry.index}" => entry }
    id = each.value.id
}
locals {
  aws_subnet_sharedsvc_ez = distinct(
    flatten(
      [for subnet in data.aws_subnet.sharedsvc_ez_each :
        {
          name = subnet.tags.Name
          id = subnet.id
        }
      ]
    )
  )
}
# output flatter_subnet_ids_sharedsvc_ez {
#   value = local.aws_subnet_sharedsvc_ez
# }

data "aws_subnet" "sharedsvc_ez" {
  for_each  = { for entry in local.aws_subnet_sharedsvc_ez: "${entry.name}" => entry }
    id = each.value.id
}
