# output "reminder" {
#   value = <<EOT
#     Remember to configure the API gateway logging to use the IAM.
#   EOT
# }

resource "local_file" "outputdata" {
  filename        = "${path.module}/../data/data.${local.path}.tf"
  file_permission = "0664"
  content         = <<EOT
###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - $${local.xxx_prefix}                                  #
#  - $${terraform.workspace}                               #
###########################################################

data "aws_lambda_function" "${var.project_code}-${var.project_desc}-ingest" {
  function_name = "$${local.lambda_prefix}-$${terraform.workspace}${var.zone}${var.tier}-${var.project_code}-${var.project_desc}-02-ingest"
}

data "aws_sqs_queues" "${var.project_code}-${var.project_desc}-sqs" {
  queue_name_prefix = "$${local.sqs_prefix}-$${terraform.workspace}${var.zone}${var.tier}-${var.project_code}-${var.project_desc}-03-fanout"
}

data "aws_sqs_queues" "${var.project_code}-${var.project_desc}-sqs-dlq" {
  queue_name_prefix = "$${local.sqs_prefix}-$${terraform.workspace}${var.zone}${var.tier}-${var.project_code}-${var.project_desc}-03-fanout-dlq"
}

data "aws_lambda_function" "${var.project_code}-${var.project_desc}-process" {
  function_name = "$${local.lambda_prefix}-$${terraform.workspace}${var.zone}${var.tier}-${var.project_code}-${var.project_desc}-04-zipappr"
}
EOT
}