
services:
  status_govtext:
    build:
      context: "../"
      target: "production"
      dockerfile: "rag/Dockerfile"
      args:
        RAG_COMPONENT_PATH: "rag/status/govtext"
        ATLAS_USER: "${ATLAS_USER}"
        ATLAS_TOKEN: "${ATLAS_TOKEN}"
        ATLAS_BASE_IMAGE: "${ATLAS_BASE_IMAGE:-registry.sgts.gitlab-dedicated.com/wog/gvt/dsaid-st/atlas/python/atlas/atlas-base}"
        ATLAS_BASE_IMAGE_TAG: "${ATLAS_BASE_IMAGE_TAG:-latest}"
        VERSION: "${VERSION:-v1.0.0}"
        RELEASE_DATE: "${RELEASE_DATE}"
        GIT_BRANCH: "${GIT_BRANCH}"
        GIT_COMMIT_HASH: "${GIT_COMMIT_HASH}"
        KEY_PASS: "${KEY_PASS}"
    image: "${REGISTRY}aibots/rag/status/govtext:${TAG:-latest}"
    container_name: status_govtext
