# output "REMINDER" {
#   value = <<-EOT
# You will also need to go to console and manually update the password

# You will also need to go to console and manually modify the Backup Retention
#   SIT > (default, 1 Day random time)
#   UAT > 3 Day 1900 UTC
#   PRD > 14 Day 1900 UTC
#   EOT
# }

resource "local_file" "outputdata" {
  filename        = "${path.module}/../data/data.${local.path}.tf"
  file_permission = "0664"
  content         = <<-EOT
###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - $${local.xxx_prefix}                                  #
#  - $${terraform.workspace}                               #
#  - $${local.route53_zone_prefix}                         #
###########################################################
# USE AS ENVIRONMENT VARIABLE
locals {
  ${upper(var.project_code)}_${upper(var.project_desc)}_OPENSEARCH__NAME = "$${data.aws_opensearchserverless_collection.${var.project_code}_${var.project_desc}.name}"
}

# no point to provide the whole list, and the aoss-picker will only need the FIRST aoss as a default.
# there after, it will update the param with the least used on schedule.
data "aws_opensearchserverless_collection" "${var.project_code}_${var.project_desc}" {
  name = "$${local.opensearch_prefix}-$${terraform.workspace}-${var.project_code}-${var.project_desc}01"
}

###########################################################
# you need to give workload iamrole access to the opensearch
###########################################################
# resource "aws_opensearchserverless_access_policy" "project" {
# # name should be the subset of your iamrole
#   name        = "$${terraform.workspace}$${var.zone}-$${var.project_code}-$${var.project_desc}"
#   type        = "data"
#   description = "read and write permissions"
#   policy = jsonencode([
#     {
#       Rules = [
#         {
#           ResourceType = "index",
#           Resource = [
#             "index/$${local.VECTORDB_OPENSEARCH__NAME}/*"
#           ],
#           Permission = [
#             "aoss:*"
#           ]
#         },
#         {
#           ResourceType = "collection",
#           Resource = [
#             "collection/$${local.VECTORDB_OPENSEARCH__NAME}"
#           ],
#           Permission = [
#             "aoss:*"
#           ]
#         }
#       ],
#       Principal = [
#         your_workload_iam_role.arn
#       ]
#     }
#   ])
# }
  EOT
}