# output "REMINDER" {
#   value = <<-EOT
# You will also need to go to console and manually update the password

# You will also need to go to console and manually modify the Backup Retention
#   SIT > (default, 1 Day random time)
#   UAT > 3 Day 1900 UTC
#   PRD > 14 Day 1900 UTC
#   EOT
# }
resource "local_file" "outputdata" {
  filename        = "${path.module}/../data/data.${local.path}.tf"
  file_permission = "0664"
  content         = <<-EOT
###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - $${local.xxx_prefix}                                  #
#  - $${terraform.workspace}                               #
#  - $${local.route53_zone_prefix}                         #
###########################################################
# USE AS ENVIRONMENT VARIABLE
locals {
  ${upper( replace(var.project_code, "-", "_") )}_${upper( replace(var.project_desc, "-", "_") )}__PARAM = "$${data.aws_ssm_parameter.${var.project_code}_${var.project_desc}.name}"
}

data "aws_ssm_parameter" "${var.project_code}_${var.project_desc}" {
  name  = "$${local.para_store_prefix}-$${terraform.workspace}${var.zone}${var.tier}-${var.project_code}-${var.project_desc}"
}

data "aws_security_group" "${var.project_code}_${var.project_desc}" {
  name  = "$${local.secgrp_prefix}-$${terraform.workspace}${var.zone}${var.tier}-${var.project_code}-${var.project_desc}"
}
  EOT
}