###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
###########################################################
# USE AS ENVIRONMENT VARIABLE
locals {
  AIBOTS_RAG_CHUNK_ZIP__SQS = "${data.aws_sqs_queue.aibots_rag-chunk_zip.url}"
  AIBOTS_RAG_CHUNK_TEXT_SEMANTIC__SQS = "${data.aws_sqs_queue.aibots_rag-chunk_text_semantic.url}"
  AIBOTS_RAG_CHUNK_TEXT_FIXED__SQS = "${data.aws_sqs_queue.aibots_rag-chunk_text_fixed.url}"
  AIBOTS_RAG_CHUNK_TEXT_ANCHORS__SQS = "${data.aws_sqs_queue.aibots_rag-chunk_text_anchors.url}"
  AIBOTS_RAG_CHUNK_DATAFRAME__SQS = "${data.aws_sqs_queue.aibots_rag-chunk_dataframe.url}"
}

data "aws_sqs_queue" "aibots_rag-chunk_zip" {
  name = "${local.sqs_prefix}-${terraform.workspace}ezapp-aibots-rag-chunk-zip"
}

data "aws_sqs_queue" "aibots_rag-chunk_text_semantic" {
  name = "${local.sqs_prefix}-${terraform.workspace}ezapp-aibots-rag-chunk-text_semantic"
}

data "aws_sqs_queue" "aibots_rag-chunk_text_fixed" {
  name = "${local.sqs_prefix}-${terraform.workspace}ezapp-aibots-rag-chunk-text_fixed"
}

data "aws_sqs_queue" "aibots_rag-chunk_text_anchors" {
  name = "${local.sqs_prefix}-${terraform.workspace}ezapp-aibots-rag-chunk-text_anchors"
}

data "aws_sqs_queue" "aibots_rag-chunk_dataframe" {
  name = "${local.sqs_prefix}-${terraform.workspace}ezapp-aibots-rag-chunk-dataframe"
}

