###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
#  - ${local.route53_zone_prefix}                         #
###########################################################
# lambda arn for:
# - cloudwatch logs subscription filter
# - SQS DLQ
data "aws_lambda_function" "notification" {
  function_name = "${local.lambda_prefix}-${terraform.workspace}ez-sharedinfra-notification"
}

# SNS for:
# cloudwatch resource monitoring
data "aws_sns_topic" "notification" {
  name = "${local.sns_prefix}-${terraform.workspace}ez-sharedinfra-notification"
}

