resource "local_file" "outputdata" {
  filename        = "${path.module}/../data/data.${local.path}.tf"
  file_permission = "0664"
  content         = <<EOT
###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - $${local.xxx_prefix}                                  #
#  - $${terraform.workspace}                               #
#  - $${local.route53_zone_prefix}                         #
###########################################################
data "aws_cognito_user_pools" "wog-aad" {
  name  = "$${local.cognito_prefix}-$${terraform.workspace}${var.zone}${var.tier}-${var.project_code}-${var.project_desc}"
}

locals {
  # resource "cognito_user_pool_domain"
  # >> domain
  # Terraform does not have a data for this.
  # This is the FQDN that you provide when you onboard to WOG AAD.
  cognito_user_pool_domain_wog-aad = "$${terraform.workspace}-sso-${var.dept}"
  
  # resource "aws_cognito_identity_provider"
  # This is the the name of aws_cognito_identity_provider.
  # Terraform does not have a data for this.
  # this is remarked here because IaC name it using aws_cognito_user_pools.wog-aad.name
  # you can unremark in you standalone setup.
  # cognito_identity_providers_wog-aad = data.aws_cognito_user_pools.wog-aad.name
}
EOT
}