###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
###########################################################
data "aws_lambda_function" "aibots-rag-aio-zip" {
  function_name = "${local.lambda_prefix}-${terraform.workspace}ezapp-aibots-rag-aio-zip"
}

data "aws_sqs_queue" "aibots-rag-aio-zip" {
  name = "${local.sqs_prefix}-${terraform.workspace}ezapp-aibots-rag-aio-zip"
}

data "aws_lambda_function" "aibots-rag-aio-img" {
  function_name = "${local.lambda_prefix}-${terraform.workspace}ezapp-aibots-rag-aio-img"
}

data "aws_sqs_queue" "aibots-rag-aio-img" {
  name = "${local.sqs_prefix}-${terraform.workspace}ezapp-aibots-rag-aio-img"
}

