###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
###########################################################
# USE AS ENVIRONMENT VARIABLE
locals {
  AIBOTS_RAG_SOURCE_ZIP__SQS = "${data.aws_sqs_queue.aibots_rag-source_zip.url}"
  AIBOTS_RAG_SOURCE_S3__SQS = "${data.aws_sqs_queue.aibots_rag-source_s3.url}"
  AIBOTS_RAG_SOURCE_URL__SQS = "${data.aws_sqs_queue.aibots_rag-source_url.url}"
}

data "aws_sqs_queue" "aibots_rag-source_zip" {
  name = "${local.sqs_prefix}-${terraform.workspace}ezapp-aibots-rag-source-zip"
}

data "aws_sqs_queue" "aibots_rag-source_s3" {
  name = "${local.sqs_prefix}-${terraform.workspace}ezapp-aibots-rag-source-s3"
}

data "aws_sqs_queue" "aibots_rag-source_url" {
  name = "${local.sqs_prefix}-${terraform.workspace}ezapp-aibots-rag-source-url"
}

