###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
###########################################################
# USE AS ENVIRONMENT VARIABLE
locals {
  AIBOTS_RAG_AOSS_PICKER__PARAM = "${data.aws_ssm_parameter.aibots_rag-aoss-picker.name}"
}

data "aws_ssm_parameter" "aibots_rag-aoss-picker" {
  name = "${local.para_store_prefix}-${terraform.workspace}ezapp-aibots-rag-aoss-picker"
}
