###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
###########################################################
# USE AS ENVIRONMENT VARIABLE
locals {
  AIBOTS_RAG_PARSE_ZIP__SQS = "${data.aws_sqs_queue.aibots_rag-parse_zip.url}"
  AIBOTS_RAG_PARSE_DOCX__SQS = "${data.aws_sqs_queue.aibots_rag-parse_docx.url}"
  AIBOTS_RAG_PARSE_XLSX__SQS = "${data.aws_sqs_queue.aibots_rag-parse_xlsx.url}"
  AIBOTS_RAG_PARSE_PPTX__SQS = "${data.aws_sqs_queue.aibots_rag-parse_pptx.url}"
  AIBOTS_RAG_PARSE_CSV__SQS = "${data.aws_sqs_queue.aibots_rag-parse_csv.url}"
  AIBOTS_RAG_PARSE_TXT__SQS = "${data.aws_sqs_queue.aibots_rag-parse_txt.url}"
  AIBOTS_RAG_PARSE_PDF__SQS = "${data.aws_sqs_queue.aibots_rag-parse_pdf.url}"
}

data "aws_sqs_queue" "aibots_rag-parse_zip" {
  name = "${local.sqs_prefix}-${terraform.workspace}ezapp-aibots-rag-parse-zip"
}

data "aws_sqs_queue" "aibots_rag-parse_docx" {
  name = "${local.sqs_prefix}-${terraform.workspace}ezapp-aibots-rag-parse-docx"
}

data "aws_sqs_queue" "aibots_rag-parse_xlsx" {
  name = "${local.sqs_prefix}-${terraform.workspace}ezapp-aibots-rag-parse-xlsx"
}

data "aws_sqs_queue" "aibots_rag-parse_pptx" {
  name = "${local.sqs_prefix}-${terraform.workspace}ezapp-aibots-rag-parse-pptx"
}

data "aws_sqs_queue" "aibots_rag-parse_csv" {
  name = "${local.sqs_prefix}-${terraform.workspace}ezapp-aibots-rag-parse-csv"
}

data "aws_sqs_queue" "aibots_rag-parse_txt" {
  name = "${local.sqs_prefix}-${terraform.workspace}ezapp-aibots-rag-parse-txt"
}

data "aws_sqs_queue" "aibots_rag-parse_pdf" {
  name = "${local.sqs_prefix}-${terraform.workspace}ezapp-aibots-rag-parse-pdf"
}

