###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
#  - ${local.route53_zone_prefix}                         #
###########################################################
# # USE AS ENVIRONMENT VARIABLE
# locals {
#   AIBOTS_RAG_OPENSEARCH__NAME = "${data.aws_opensearchserverless_collection.aibots_rag.name}"
# }

# # no point to provide the whole list, and the aoss-picker will only need the FIRST aoss as a default.
# # there after, it will update the param with the least used on schedule.
# data "aws_opensearchserverless_collection" "aibots_rag" {
#   name = "${local.opensearch_prefix}-${terraform.workspace}-aibots-rag01"
# }

###########################################################
# you need to give workload iamrole access to the opensearch
###########################################################
# resource "aws_opensearchserverless_access_policy" "project" {
# # name should be the subset of your iamrole
#   name        = "${terraform.workspace}${var.zone}-${var.project_code}-${var.project_desc}"
#   type        = "data"
#   description = "read and write permissions"
#   policy = jsonencode([
#     {
#       Rules = [
#         {
#           ResourceType = "index",
#           Resource = [
#             "index/${local.VECTORDB_OPENSEARCH__NAME}/*"
#           ],
#           Permission = [
#             "aoss:*"
#           ]
#         },
#         {
#           ResourceType = "collection",
#           Resource = [
#             "collection/${local.VECTORDB_OPENSEARCH__NAME}"
#           ],
#           Permission = [
#             "aoss:*"
#           ]
#         }
#       ],
#       Principal = [
#         your_workload_iam_role.arn
#       ]
#     }
#   ])
# }
