###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
###########################################################
# USE AS ENVIRONMENT VARIABLE
locals {
  AIBOTS_RAG_EMBED_ZIP__SQS = "${data.aws_sqs_queue.aibots_rag-embed_zip.url}"
  AIBOTS_RAG_EMBED_OPENSEARCH__SQS = "${data.aws_sqs_queue.aibots_rag-embed_opensearch.url}"
}

data "aws_sqs_queue" "aibots_rag-embed_zip" {
  name = "${local.sqs_prefix}-${terraform.workspace}ezapp-aibots-rag-embed-zip"
}

data "aws_sqs_queue" "aibots_rag-embed_opensearch" {
  name = "${local.sqs_prefix}-${terraform.workspace}ezapp-aibots-rag-embed-opensearch"
}

