output reminder {
  value = <<EOT
  Remember to set the notification information in the ${aws_ssm_parameter.notification.name}
  EOT
}



resource "local_file" "outputdata-secret" {
  filename        = "${path.module}/../data/data.${local.path}.secret.tf"
  file_permission = "0664"
  content         = <<EOT
###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - $${local.xxx_prefix}                                  #
#  - $${terraform.workspace}                               #
#  - $${local.route53_zone_prefix}                         #
###########################################################
################################################################################
# # nacl is different from subnets route_tables and security_groups
# # nacl does not have a data.aws_network_acl
# # it only has nacl.aws_network_acls (note the S) which only return a list of nacl_ids
# # the typical auto gen with vpc_id will not work.
################################################################################
# USE AS ENVIRONMENT VARIABLE
locals {
  ${upper(var.project_code)}__${upper(local.secret_prefix)} = "$${data.aws_secretsmanager_secrets.${var.project_code}-secret.name}"
}

data "aws_secretsmanager_secrets" "${var.project_code}-secret" {
  filter {
    name   = "tag:Terraform"
    values = ["true"]
  }
  filter {
    name   = "tag:Environment"
    values = ["$${terraform.workspace}"]
  }
  filter {
    name   = "tag:Project-Code"
    values = ["${var.project_code}"]
  }
  filter {
    name   = "tag:Project-Desc"
    values = ["${var.project_desc}"]
  }
  filter {
    name   = "tag:Zone"
    values = ["${var.zone}"]
  }
}
EOT
}



resource "local_file" "outputdata-notification" {
  filename        = "${path.module}/../data/data.${local.path}.notification.tf"
  file_permission = "0664"
  content         = <<EOT
###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - $${local.xxx_prefix}                                  #
#  - $${terraform.workspace}                               #
#  - $${local.route53_zone_prefix}                         #
###########################################################
################################################################################
# # nacl is different from subnets route_tables and security_groups
# # nacl does not have a data.aws_network_acl
# # it only has nacl.aws_network_acls (note the S) which only return a list of nacl_ids
# # the typical auto gen with vpc_id will not work.
################################################################################
data "aws_ssm_parameter" "${var.project_code}-notification" {
  name  = "$${local.para_store_prefix}-$${terraform.workspace}${var.zone}-${var.project_code}-notification"
}
EOT
}



resource "local_file" "outputdata-vpc" {
  count = var.vpc_cidr_block == null ? 0 : 1

  filename        = "${path.module}/../data/data.${local.path}.vpc.tf"
  file_permission = "0664"
  content         = <<EOT
###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - $${local.xxx_prefix}                                  #
#  - $${terraform.workspace}                               #
#  - $${local.route53_zone_prefix}                         #
###########################################################
data "aws_vpc" "${var.project_code}_${var.zone}" {
  filter {
    name   = "tag:Terraform"
    values = ["true"]
  }
  filter {
    name   = "tag:Environment"
    values = ["$${terraform.workspace}"]
  }
  filter {
    name   = "tag:Project-Code"
    values = ["${var.project_code}"]
  }
  filter {
    name   = "tag:Zone"
    values = ["${var.zone}"]
  }
}
EOT
}



resource "local_file" "outputdata-igw" {
  count = var.deploy_igw ? 1 : 0

  filename        = "${path.module}/../data/data.${local.path}.igw.tf"
  file_permission = "0664"
  content         = <<EOT
###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - $${local.xxx_prefix}                                  #
#  - $${terraform.workspace}                               #
#  - $${local.route53_zone_prefix}                         #
###########################################################
data "aws_internet_gateway" "${var.project_code}_${var.zone}" {
  filter {
    name   = "tag:Terraform"
    values = ["true"]
  }
  filter {
    name   = "tag:Environment"
    values = ["$${terraform.workspace}"]
  }
  filter {
    name   = "tag:Project-Code"
    values = ["${var.project_code}"]
  }
  filter {
    name   = "tag:Zone"
    values = ["${var.zone}"]
  }
}
EOT
}



resource "local_file" "outputdata-subnets" {
  filename        = "${path.module}/../data/data.${local.path}.subnets.tf"
  file_permission = "0664"
  content         = <<EOT
###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - $${local.xxx_prefix}                                  #
#  - $${terraform.workspace}                               #
#  - $${local.route53_zone_prefix}                         #
###########################################################
################################################################################
# # This part will auto generate the data for the subnets with a VPC.
################################################################################
data "aws_subnets" "${var.project_code}_${var.zone}_all" {
  filter {
    name   = "vpc-id"
    values = [ data.aws_vpc.${var.project_code}_${var.zone}.id ]
  }
  filter {
    name   = "tag:Terraform"
    values = [ "true" ]
  }
  filter {
    name   = "tag:Environment"
    values = ["$${terraform.workspace}"]
  }
}
# output aws_subnets_${var.project_code}_${var.zone}_all_ids {
#   value = data.aws_subnets.${var.project_code}_${var.zone}_all.ids
# }

locals {
  subnet_ids_${var.project_code}_${var.zone} = flatten(
    [for index in range( length( data.aws_subnets.${var.project_code}_${var.zone}_all.ids ) ) :
      {
        index = index
        id = data.aws_subnets.${var.project_code}_${var.zone}_all.ids[index]
      }
    ]
  )
}
# output flatter_subnet_ids_${var.project_code}_${var.zone} {
#   value = local.subnet_ids_${var.project_code}_${var.zone}
# }

data "aws_subnet" "${var.project_code}_${var.zone}_each" {
  for_each  = { for entry in local.subnet_ids_${var.project_code}_${var.zone}: "$${entry.index}" => entry }
    id = each.value.id
}
locals {
  aws_subnet_${var.project_code}_${var.zone} = distinct(
    flatten(
      [for subnet in data.aws_subnet.${var.project_code}_${var.zone}_each :
        {
          name = subnet.tags.Name
          id = subnet.id
        }
      ]
    )
  )
}
# output flatter_subnet_ids_${var.project_code}_${var.zone} {
#   value = local.aws_subnet_${var.project_code}_${var.zone}
# }

data "aws_subnet" "${var.project_code}_${var.zone}" {
  for_each  = { for entry in local.aws_subnet_${var.project_code}_${var.zone}: "$${entry.name}" => entry }
    id = each.value.id
}
EOT
}



resource "local_file" "outputdata-route_tables" {
  filename        = "${path.module}/../data/data.${local.path}.route_tables.tf"
  file_permission = "0664"
  content         = <<EOT
###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - $${local.xxx_prefix}                                  #
#  - $${terraform.workspace}                               #
#  - $${local.route53_zone_prefix}                         #
###########################################################
################################################################################
# # This part will auto generate the data for the route_tables with a VPC.
################################################################################
data "aws_route_tables" "${var.project_code}_${var.zone}_all" {
  filter {
    name   = "vpc-id"
    values = [ data.aws_vpc.${var.project_code}_${var.zone}.id ]
  }
  filter {
    name   = "tag:Terraform"
    values = [ "true" ]
  }
  filter {
    name   = "tag:Environment"
    values = ["$${terraform.workspace}"]
  }
}
# output aws_route_tables {
#   value = data.aws_route_tables.${var.project_code}_${var.zone}_all
# }

locals {
  route_table_ids_${var.project_code}_${var.zone} = flatten(
    [for index in range( length( data.aws_route_tables.${var.project_code}_${var.zone}_all.ids ) ) :
      {
        index = index
        route_table_id = data.aws_route_tables.${var.project_code}_${var.zone}_all.ids[index]
      }
    ]
  )
}
# output flatter_route_table_ids_${var.project_code}_${var.zone} {
#   value = local.route_table_ids_${var.project_code}_${var.zone}
# }

data "aws_route_table" "${var.project_code}_${var.zone}_each" {
  for_each  = { for entry in local.route_table_ids_${var.project_code}_${var.zone}: "$${entry.index}" => entry }
    route_table_id = each.value.route_table_id
}
locals {
  aws_route_table_${var.project_code}_${var.zone} = distinct(
    flatten(
      [for route_table in data.aws_route_table.${var.project_code}_${var.zone}_each :
        {
          name = route_table.tags.Name
          route_table_id = route_table.route_table_id
        }
      ]
    )
  )
}
# output flatter_route_table_ids_${var.project_code}_${var.zone} {
#   value = local.aws_route_table_${var.project_code}_${var.zone}
# }

data "aws_route_table" "${var.project_code}_${var.zone}" {
  for_each  = { for entry in local.aws_route_table_${var.project_code}_${var.zone}: "$${entry.name}" => entry }
    route_table_id = each.value.route_table_id
}
EOT
}



resource "local_file" "outputdata-security_groups" {
  filename        = "${path.module}/../data/data.${local.path}.security_groups.tf"
  file_permission = "0664"
  content         = <<EOT
###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - $${local.xxx_prefix}                                  #
#  - $${terraform.workspace}                               #
#  - $${local.route53_zone_prefix}                         #
###########################################################
################################################################################
# # This part will auto generate the data for the security_groups with a VPC.
################################################################################
data "aws_security_groups" "${var.project_code}_${var.zone}_all" {
  filter {
    name   = "vpc-id"
    values = [ data.aws_vpc.${var.project_code}_${var.zone}.id ]
  }
  filter {
    name   = "tag:Terraform"
    values = [ "true" ]
  }
  filter {
    name   = "tag:Environment"
    values = ["$${terraform.workspace}"]
  }
}
# output aws_security_groups_all_ids {
#   value = data.aws_security_groups.${var.project_code}_${var.zone}_all.ids
# }

locals {
  security_group_ids_${var.project_code}_${var.zone} = flatten(
    [for index in range( length( data.aws_security_groups.${var.project_code}_${var.zone}_all.ids ) ) :
      {
        index = index
        id = data.aws_security_groups.${var.project_code}_${var.zone}_all.ids[index]
      }
    ]
  )
}
# output flatter_security_group_ids {
#   value = local.security_group_ids_${var.project_code}_${var.zone}
# }

data "aws_security_group" "${var.project_code}_${var.zone}_each" {
  for_each  = { for entry in local.security_group_ids_${var.project_code}_${var.zone}: "$${entry.index}" => entry }
    id = each.value.id
}
locals {
  aws_security_group_${var.project_code}_${var.zone}_each = distinct(
    flatten(
      [for security_group in data.aws_security_group.${var.project_code}_${var.zone}_each :
        {
          name = security_group.tags.Name
          id = security_group.id
        }
      ]
    )
  )
}
# output flatter_security_group_ids {
#   value = local.aws_security_group_${var.project_code}_${var.zone}_each
# }

data "aws_security_group" "${var.project_code}_${var.zone}" {
  for_each  = { for entry in local.aws_security_group_${var.project_code}_${var.zone}_each: "$${entry.name}" => entry }
    id = each.value.id
}
EOT
}



resource "local_file" "outputdata-nacls" {
  filename        = "${path.module}/../data/data.${local.path}.nacls.tf"
  file_permission = "0664"
  content         = <<EOT
###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - $${local.xxx_prefix}                                  #
#  - $${terraform.workspace}                               #
#  - $${local.route53_zone_prefix}                         #
###########################################################
################################################################################
# # nacl is different from subnets route_tables and security_groups
# # nacl does not have a data.aws_network_acl
# # it only has nacl.aws_network_acls (note the S) which only return a list of nacl_ids
# # the typical auto gen with vpc_id will not work.
################################################################################
data "aws_network_acls" "${var.project_code}_${var.zone}_all" {
  filter {
    name   = "tag:Terraform"
    values = ["true"]
  }
  filter {
    name   = "tag:Environment"
    values = ["$${terraform.workspace}"]
  }
  filter {
    name   = "tag:Project-Code"
    values = ["${var.project_code}"]
  }
  filter {
    name   = "tag:Zone"
    values = ["${var.zone}"]
  }
}

%{for nacl in aws_network_acl.project~}
data "aws_network_acls" "${nacl.tags.Project-Code}_${nacl.tags.Zone}_${nacl.tags.Tier}" {
  filter {
    name   = "tag:Terraform"
    values = ["true"]
  }
  filter {
    name   = "tag:Environment"
    values = ["$${terraform.workspace}"]
  }
  filter {
    name   = "tag:Project-Code"
    values = ["${nacl.tags.Project-Code}"]
  }
  filter {
    name   = "tag:Zone"
    values = ["${nacl.tags.Zone}"]
  }
  filter {
    name   = "tag:Tier"
    values = ["${nacl.tags.Tier}"]
  }
}

%{endfor~}
EOT
}