from __future__ import annotations

from datetime import datetime
from typing import Annotated

from aibots.constants import (
    DEFAULT_SYSTEM_PROMPT_TEMPLATE,
    DEFAULT_SYSTEM_PROMPT_VARIABLES,
)
from aibots.models import (
    Agent as BaseAgent,
)
from aibots.models import (
    AgentChatConfig as BaseAgentChatConfig,
)
from aibots.models import (
    AgentReleaseState as BaseAgentReleaseState,
)
from aibots.models import (
    AgentSharing as BaseAgentSharing,
)
from atlas.genai.schemas import PromptTemplate
from atlas.schemas import Uuid
from beanie import Document
from pydantic import AnyUrl, Field

__doc__ = """
Contains all data structures associated with Launchpad Agents
"""

__all__ = (
    "AgentChatConfig",
    "AgentSharing",
    "AgentReleaseState",
    "Agent",
    "AgentDB",
)


class AgentChatConfig(BaseAgentChatConfig):
    """
    Configurable chat parameters

    Attributes:
        model (ModelID | None): LLM model associated with Chat Message
        user_prompt (PromptTemplate): User Prompt template
        system_prompt (PromptTemplate): System prompt template
        params (dict[str, Any]): AI Model parameters used to generate
                    the Chat Message, defaults to an empty dictionary
        properties (dict[str, Any]): Additional properties used in
                    the business logic, defaults to an empty dictionary
    """

    user_prompt: Annotated[
        PromptTemplate | None, Field(None, validation_alias="userPrompt")
    ]
    system_prompt: Annotated[
        PromptTemplate,
        Field(
            PromptTemplate(
                template=DEFAULT_SYSTEM_PROMPT_TEMPLATE,
                variables=DEFAULT_SYSTEM_PROMPT_VARIABLES,
            ),
            validation_alias="systemPrompt",
        ),
    ]


class AgentSharing(BaseAgentSharing):
    """
    Sharing details of the Agent

    Attributes:
        url_path (str): URL path fragment of the Agent, should be
                        unique, defaults to autogenerated string
        public_url (AnyUrl | str | None): Public URL to the agent,
                                          based on url_path, defaults
                                          to None
        api_url (AnyUrl | str | None): API endpoint to the Agent, based
                                       on url_path, defaults to None
        api_keys (list[Uuid]): API Keys associated with the Agent, defaults
                               to an empty list
    """

    url_path: Annotated[str, Field(validation_alias="urlPath")]
    public_url: Annotated[
        AnyUrl | str | None, Field(None, validation_alias="publicUrl")
    ]
    api_url: Annotated[
        AnyUrl | str | None, Field(None, validation_alias="apiUrl")
    ]
    api_keys: Annotated[list[Uuid], Field([], validation_alias="apiKeys")]


class AgentReleaseState(BaseAgentReleaseState):
    """
    Tracks the release status of the agent

    Attributes:
        state (DeploymentState): Deployment state, defaults to alpha
        created (datetime | None): Creation timestamp of Agent Release State,
                                   defaults to None
        last_modified (datetime | None): Last modified timestamp of Agent
                                         Release State, defaults to None
        last_modified_user (Uuid | str | None): Last modified user of Agent
                                                Release State, defaults to None
        denied (bool | None): Indicates if Agent has been denied, defaults to
                              None
        comments (list[Comment]): List of comments, defaults to an
                                  empty list
    """

    last_modified: Annotated[
        datetime | None, Field(None, validation_alias="lastModified")
    ]
    last_modified_user: Annotated[
        Uuid | None, Field(None, validation_alias="lastModifiedUser")
    ]


class Agent(BaseAgent):
    """
    Schema of a Agent configuration

    Attributes:
        id (Uuid): UUID string
        name (constr): Name of the Agent
        description (constr): Brief description of the Agent
        featured (bool): Indicates if the Agent is featured,
                         defaults to False
        clone (Uuid | None): Indicates if the Agent is cloned
        sharing (AgentSharing): Sharing details of the Agent
        ownership (Ownership | None): Ownership details
        files (list[Uuid] | None): Non-embedded files associated
                            with the Agent
        agency (str): Agency associated with the Agent
        welcome_message (str): Welcome message the Agent will display when a
                               new chat is created
        templates (list[AgentTemplate]): Default templates to use
                                        with the Agent
        release_state (AgentReleaseState):  Represents the release status
                                            of the Agent, defaults to
                                            default release state values
        knowledge_bases (list[Uuid]): Knowledge Bases associated with Agent,
                                     defaults to an empty list
        default_pipeline (Uuid | None): Default RAG pipeline, defaults to
                                        None
        rags (list[Uuid]): RAG configuration for the Agent, defaults to an
                           empty list
        chat (AgentChatConfig): Chat configuration for the Agent,
                                defaults to default AgentChatConfig
                                values
        tools (list[Uuid]): Tools that the Agent is able to access,
                            defaults to an empty list
        settings (dict[str, Any]): Additional settings associated
                                   with the Agent, defaults to an empty
                                   dictionary
        tags (list[str]): Tags associated with the Agent, defaults to
                          an empty list
        meta (Meta): Meta information associated with the Agent
        modifications (Modifications): Modifications made to the Agent,
                                       defaults to an empty dictionary
    """

    sharing: AgentSharing | None = None
    release_state: Annotated[
        AgentReleaseState,
        Field(AgentReleaseState(), validation_alias="releaseState"),
    ]
    chat: AgentChatConfig = AgentChatConfig()


class AgentDB(Agent, Document):
    """
    Schema of a Agent to be stored in MongoDB

    Attributes:
        id (Uuid): UUID string
        name (constr): Name of the Agent
        description (constr): Brief description of the Agent
        featured (bool): Indicates if the Agent is featured,
                         defaults to False
        clone (Uuid | None): Indicates if the Agent is cloned
        sharing (AgentSharing): Sharing details of the Agent
        ownership (Ownership | None): Ownership details
        files (list[Uuid] | None): Non-embedded files associated
                            with the Agent
        agency (str): Agency associated with the Agent
        welcome_message (str): Welcome message the Agent will display when a
                               new chat is created
        templates (list[AgentTemplate]): Default templates to use
                                        with the Agent
        release_state (AgentReleaseState):  Represents the release status
                                            of the Agent, defaults to
                                            default release state values
        knowledge_bases (list[Uuid]): Knowledge Bases associated with Agent,
                                     defaults to an empty list
        default_pipeline (Uuid | None): Default RAG pipeline, defaults to
                                        None
        rags (list[Uuid]): RAG configuration for the Agent, defaults to an
                           empty list
        chat (AgentChatConfig): Chat configuration for the Agent,
                                defaults to default AgentChatConfig
                                values
        tools (list[Uuid]): Tools that the Agent is able to access,
                            defaults to an empty list
        settings (dict[str, Any]): Additional settings associated
                                   with the Agent, defaults to an empty
                                   dictionary
        tags (list[str]): Tags associated with the Agent, defaults to
                          an empty list
        meta (Meta): Meta information associated with the Agent
        modifications (Modifications): Modifications made to the Agent,
                                       defaults to an empty dictionary
    """

    class Settings:
        name: str = "agents"
