from __future__ import annotations

from aibots.models import ChatFull, ChatMessage
from beanie import Document

__doc__ = """
Data models for Chats, includes reusable fields and MongoDB schema models
"""

__all__ = ("ChatMessageDB", "ChatDB")


class ChatMessageDB(ChatMessage, Document):
    """
    MongoDB representation of a ChatMessage

    Attributes:
        id (Uuid): UUID string, autogenerated
        chat (Uuid): UUID reference to the Chat, defaults to None
        query (ChatInteraction): Query to the LLM
        response (ChatInteraction | None): Response from the LLM, defaults to
                                           None
        tokens (Tokens): Number of tokens consumed by the interaction, defaults to
                         default Tokens values
        model (ModelID): LLM model associated with Chat Message, inherited
        system_prompt (ChatInteraction | None): System prompt template, defaults to
                                                None
        params (dict[str, Any]): AI Model parameters used to generate the Chat Message,
                                 inherited
        properties (dict[str, Any]): Additional properties used in the business logic,
                                     inherited
        liked (bool | None): Indicates if the message has been liked, defaults to None
        pinned (bool): Indicates if the message has been pinned, defaults to False
        rag (RAGQuery): RAG query details retrieved from the RAG pipeline, defaults to
                        the default RAGQuery details
    """  # noqa: E501

    class Settings:
        name: str = "messages"


class ChatDB(ChatFull, Document):
    """
    MongoDB schema of full chat conversation with historical messages.

    Attributes:
        id (Uuid): UUID string, inherited
        name (constr): Name field, only allows hexadecimal values,
                       hyphen and underscore, inherited
        agents (list[Uuid]): List of Agent IDs associated with the Chat
        user_prompt (PromptTemplate | None): User prompt template, inherited
        modifications (ModificationDict): Modifications made to the Chat, inherited
        messages (list[Uuid] | list[ChatMessage]): Chat Messages associated with the
                                                   conversation, defaults to an empty
                                                   list
        agents (list[Uuid]): List of agents associated with the Chat, defaults to an
                             empty list

        tokens (ChatTokens): Number of tokens cumulatively consumed, inherited
        model (ModelID): LLM model associated with Chat Message, inherited
        system_prompt (PromptTemplate): System prompt template, defaults
                                        to default Prompt Template values
        params (dict[str, Any]): AI Model parameters used to generate the Chat Message,
                                 inherited
        properties (dict[str, Any]): Additional properties used in the business logic,
                                     inherited
    """  # noqa: E501

    class Settings:
        name: str = "chats"
