from __future__ import annotations

from aibots.models import File
from beanie import Document

__all__ = ("FileDB",)


class FileDB(File, Document):
    """
    Generic structure of a File stored in Atlas

    Attributes:
        id (Uuid): UUID string, autogenerated, inherited
        name (Optional[str]): Name field with no length restriction,
                                    defaults to None
        folder (str): Virtual folder name of the File, defaults to '/'
        versions (Union[int, str]): List of all uploaded versions of
                                    the File, defaults to [1]
        content (Optional[str]): Internal path link to the latest
                                 version of the file, defaults to None
        metadata (dict[str, Any]): Metadata associated with content,
                                   defaults to an empty dictionary
        ownership (Ownership): Ownership details of the file
        meta (Meta): Metadata associated with the resource,
                     defaults to the default Meta values
        modifications (ModificationDict): Modification details,
                                          defaults to an empty
                                          dictionary
    """

    class Settings:
        name: str = "files"
