from __future__ import annotations

from aibots.models import RAGConfig
from beanie import Document

__all__ = ("RAGConfigDB",)


class RAGConfigDB(RAGConfig, Document):
    """
    RAG pipelines and configuration associated with a Agent

    Attributes:
        id (Uuid): UUID string, autogenerated
        type (str): RAG pipeline type, one of the supported
                    RAG pipelines
        config (dict[str, Any]): RAG pipeline configuration, defaults
                                 to an empty dictionary
        agent (Uuid | None): ID of associated Agent, defaults to None
        retrieval (dict[str, Any]): Retrieval details, defaults to an
                                    empty dictionary
        timestamp (datetime): Timestamp when RAG pipeline config was
                              created, defaults to the current datetime
    """

    class Settings:
        name: str = "rag_configs"
