###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
#  - ${local.route53_zone_prefix}                         #
###########################################################
# USE AS ENVIRONMENT VARIABLE
locals {
  SHAREDSVC_LATIOS_API__PUB_URL = "https://not_set${local.route53_zone_prefix}data.tech.gov.sg:443"
  SHAREDSVC_LATIOS_API__PTE_URL = "https://latios-api.${local.route53_zone_prefix}data.tech.gov.sg:443"
  # SHAREDSVC_LATIOS_API__PUB_URL = "https://not_set.data.tech.gov.sg:443"
  # SHAREDSVC_LATIOS_API__PTE_URL = "https://latios-api.data.tech.gov.sg:443"
}

# data "aws_ecr_repository" "sharedsvc-nous-api" {
#   name = "${local.ecr_prefix}-${terraform.workspace}ezapp-sharedsvc-nous-api"
# }
