###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
#  - ${local.route53_zone_prefix}                         #
###########################################################
# USE AS ENVIRONMENT VARIABLE
locals {
  PUB_URL = "${data.aws_route53_zone.aibots_gov_sg.name}"
  PTE_URL = "internal.${data.aws_route53_zone.aibots_gov_sg.name}"
}

data "aws_route53_zone" "aibots_gov_sg" {
  name         = "${local.route53_zone_prefix}aibots.gov.sg"
  private_zone = true
}
