resource "local_file" "outputdata" {
  filename = "${path.module}/../data/data.${local.path}.tf"
  file_permission      = "0664"
  content  = <<-EOT
###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - $${local.xxx_prefix}                                  #
#  - $${terraform.workspace}                               #
#  - $${local.route53_zone_prefix}                         #
###########################################################
locals{
  default_lambda_runtime = "python3.12"
}

%{ for layer in var.lambda_layers ~}
data "aws_lambda_layer_version" "${layer.layer_name}" {
  layer_name  = "$${local.lambda_layer_prefix}-$${terraform.workspace}-${layer.layer_name}"
}

%{ endfor ~}
data "aws_lambda_layer_version" "awswrangler" {
  layer_name = "arn:aws:lambda:ap-southeast-1:336392948345:layer:AWSSDKPandas-Python312"
  version    = 4
}

data "aws_lambda_layer_version" "LambdaInsightsExtension" {
  layer_name  = "arn:aws:lambda:ap-southeast-1:580247275435:layer:LambdaInsightsExtension"
  version    = 53
}
  EOT
}