from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Annotated, Any

from atlas.genai.schemas import (
    AtlasLLMInteractionBase,
    ModelID,
    PromptTemplate,
)
from atlas.mixins import CUDMixin, PermissionsMixin
from atlas.schemas import (
    AtlasID,
    DescriptiveName,
    Modifications,
    Ownership,
    Uuid,
)
from atlas.utils import generate_curr_datetime
from pydantic import AnyUrl, BaseModel, ConfigDict, Field

from aibots.constants import (
    DEFAULT_AGENT_WELCOME_MESSAGE,
    DEFAULT_LLM_MODEL_ID,
    DEFAULT_SYSTEM_PROMPT_TEMPLATE,
    DEFAULT_SYSTEM_PROMPT_VARIABLES,
)

__doc__ = """
Contains all data structures associated with Launchpad Agents
"""

__all__ = (
    "Agent",
    "AgentTemplate",
    "AgentSharing",
    "AgentChatConfig",
    "AgentReleaseState",
    "Comment",
    "DeploymentState",
)


class DeploymentState(str, Enum):
    """
    Various deployment state types of a Agent

    Attributes:
        alpha (str): Agent is in alpha testing state
        beta (str): Agent is in beta testing state
        pending (str): Agent is pending approval for production
        production (str): Agent has been approved for production
    """

    alpha = "alpha"
    beta = "beta"
    pending = "pending"
    production = "production"


class Comment(BaseModel):
    """
    Additional Comment appended to the agent

    Attributes:
        user (Uuid): User who left the comment
        comment (str): Comment details
        timestamp (datetime): Timestamp when comment was left,
                              defaults to current datetime
    """

    user: Uuid
    comment: str = ""
    timestamp: datetime = Field(default_factory=generate_curr_datetime)


class AgentReleaseState(BaseModel):
    """
    Tracks the release status of the agent

    Attributes:
        state (DeploymentState): Deployment state, defaults to alpha
        created (datetime | None): Creation timestamp of Agent Release State,
                                   defaults to None
        last_modified (datetime | None): Last modified timestamp of Agent
                                         Release State, defaults to None
        last_modified_user (Uuid | str | None): Last modified user of Agent
                                                Release State, defaults to None
        denied (bool | None): Indicates if Agent has been denied, defaults to
                              None
        comments (list[Comment]): List of comments, defaults to an
                                  empty list
    """

    model_config: ConfigDict = ConfigDict(extra="allow", populate_by_name=True)

    state: DeploymentState = DeploymentState.beta
    created: datetime | None = None
    last_modified: Annotated[
        datetime | None, Field(None, alias="lastModified")
    ]
    last_modified_user: Annotated[
        Uuid | None, Field(None, alias="lastModifiedUser")
    ]
    denied: bool | None = None
    comments: list[Comment] = []


class AgentTemplate(BaseModel):
    """
    Template call details

    Attributes:
        title (str): Display title of the template
        template (str): Value of the template
    """

    model_config: ConfigDict = ConfigDict(extra="allow", populate_by_name=True)

    title: str
    template: str


class AgentChatConfig(AtlasLLMInteractionBase):
    """
    Configurable chat parameters

    Attributes:
        model (ModelID): LLM model associated with Chat Message
        user_prompt (PromptTemplate): User Prompt template
        system_prompt (PromptTemplate): System prompt template
        params (dict[str, Any]): AI Model parameters used to generate
                    the Chat Message, defaults to an empty dictionary
        properties (dict[str, Any]): Additional properties used in
                    the business logic, defaults to an empty dictionary
    """

    user_prompt: Annotated[
        PromptTemplate | None, Field(None, alias="userPrompt")
    ]
    system_prompt: Annotated[
        PromptTemplate,
        Field(
            PromptTemplate(
                template=DEFAULT_SYSTEM_PROMPT_TEMPLATE,
                variables=DEFAULT_SYSTEM_PROMPT_VARIABLES,
            ),
            alias="systemPrompt",
        ),
    ]
    model: ModelID = DEFAULT_LLM_MODEL_ID


class AgentSharing(BaseModel):
    """
    Sharing details of the Agent

    Attributes:
        url_path (str): URL path fragment of the Agent, should be
                        unique, defaults to autogenerated string
        public_url (AnyUrl | str | None): Public URL to the agent,
                                          based on url_path, defaults
                                          to None
        api_url (AnyUrl | str | None): API endpoint to the Agent, based
                                       on url_path, defaults to None
        api_keys (list[Uuid]): API Keys associated with the Agent, defaults
                               to an empty list
    """

    model_config: ConfigDict = ConfigDict(extra="allow", populate_by_name=True)

    url_path: Annotated[str, Field(alias="urlPath")]
    public_url: Annotated[AnyUrl | str | None, Field(None, alias="publicUrl")]
    api_url: Annotated[AnyUrl | str | None, Field(None, alias="apiUrl")]
    api_keys: Annotated[list[Uuid], Field([], alias="apiKeys")]


class Agent(
    AtlasID, DescriptiveName, Modifications, CUDMixin, PermissionsMixin
):
    """
    Schema of a Agent configuration

    Attributes:
        id (Uuid): UUID string
        name (constr): Name of the Agent
        description (constr): Brief description of the Agent
        featured (bool): Indicates if the Agent is featured,
                         defaults to False
        clone (Uuid | None): Indicates if the Agent is cloned
        sharing (AgentSharing): Sharing details of the Agent
        ownership (Ownership | None): Ownership details
        files (list[Uuid]): Non-embedded files associated
                            with the Agent
        agency (str): Agency associated with the Agent
        welcome_message (str): Welcome message the Agent will display when a
                               new chat is created
        templates (list[AgentTemplate]): Default templates to use
                                        with the Agent
        release_state (AgentReleaseState):  Represents the release status
                                            of the Agent, defaults to
                                            default release state values
        knowledge_bases (list[Uuid]): Knowledge Bases associated with Agent,
                                     defaults to an empty list
        default_pipeline (Uuid | None): Default RAG pipeline, defaults to
                                        None
        rags (list[Uuid]): RAG configuration for the Agent, defaults to an
                           empty list
        chat (AgentChatConfig): Chat configuration for the Agent,
                                defaults to default AgentChatConfig
                                values
        tools (list[Uuid]): Tools that the Agent is able to access,
                            defaults to an empty list
        settings (dict[str, Any]): Additional settings associated
                                   with the Agent, defaults to an empty
                                   dictionary
        tags (list[str]): Tags associated with the Agent, defaults to
                          an empty list
        meta (Meta): Meta information associated with the Agent
        modifications (Modifications): Modifications made to the Agent,
                                       defaults to an empty dictionary
    """

    featured: bool = False
    clone: Uuid | None = None
    sharing: AgentSharing | None = None
    ownership: Ownership | None = None
    files: list[Uuid] = []
    agency: str
    welcome_message: Annotated[
        str, Field(DEFAULT_AGENT_WELCOME_MESSAGE, alias="welcomeMessage")
    ]
    templates: list[AgentTemplate] = []
    release_state: Annotated[
        AgentReleaseState, Field(AgentReleaseState(), alias="releaseState")
    ]
    knowledge_bases: Annotated[list[Uuid], Field([], alias="knowledgeBases")]
    default_pipeline: Annotated[
        Uuid | None, Field(None, alias="defaultPipeline")
    ]
    rags: list[Uuid] = []
    chat: AgentChatConfig = AgentChatConfig()
    tools: list[Uuid] = []
    settings: dict[str, Any] = {}
    tags: list[str] = []
