from __future__ import annotations

from datetime import datetime
from typing import Any

from atlas.schemas import AtlasID, ExecutionState, State, Uuid
from atlas.utils import generate_curr_datetime
from pydantic import Field

from aibots.constants import DEFAULT_RAG_PIPELINE_TYPE

__all__ = ("RAGConfig",)


class RAGConfig(AtlasID):
    """
    RAG pipelines and configuration associated with an Agent

    Attributes:
        id (Uuid): UUID string, autogenerated
        type (str): RAG pipeline type, one of the supported
                    RAG pipelines
        config (dict[str, Any]): RAG pipeline configuration, defaults
                                 to an empty dictionary
        agent (Uuid | None): ID of associated Agent, defaults to None
        retrieval (dict[str, Any]): Retrieval details, defaults to an
                                    empty dictionary
        current (State): Current execution state, defaults to the
                         pending state
        previous (State | None): Previous execution state, defaults to
                                 None
        timestamp (datetime): Timestamp when RAG pipeline config was
                              created, defaults to the current datetime
    """

    type: str = DEFAULT_RAG_PIPELINE_TYPE
    config: dict[str, Any] = {}
    agent: Uuid | None = None
    retrieval: dict[str, Any] = {}
    current: State = State(state=ExecutionState.pending)
    previous: State | None = None
    timestamp: datetime = Field(default_factory=generate_curr_datetime)

    def __eq__(self, other: RAGConfig) -> bool:
        """
        Checks if 2 AgentRAGConfigs are equivalent

        Args:
            other (RAGConfig): Another AgentRAGConfig

        Returns:
            bool: Indicates if the 2 configs are equal
        """
        return (
            self.type == other.type
            and len(self.config) == len(other.config)
            and all(v == other.config[k] for k, v in self.config.items())
        )

    def initialised(self, required: list[str]) -> bool:
        """
        Indicates if the RAG config has already been initialised
        i.e. run once

        Args:
            required (list[str]): List of required keys

        Returns:
            bool: RAG Config has been initialised
        """
        return all(i in self.retrieval for i in required)

    def update_state(self, new_state: ExecutionState, **details: Any) -> None:
        """
        Convenience function to update the RAG Config state

        Args:
            new_state (ExecutionState): New RAG Config state
            **details (Any): Additional details

        Returns:
            None
        """
        self.previous = self.current
        self.current = State(state=new_state, details=details)
