data "aws_region" "current" {} # ${data.aws_region.current.name}

data "aws_caller_identity" "current" {} # ${data.aws_caller_identity.current.account_id}

################################################################################
# This is the default tagging that your resources will be tagged with.
# This is a standard across all the modules.
################################################################################
locals {
  tags = {
    "Terraform" = "true"
    "Agency-Code" = "${var.tags.Agency-Code}"
    "Dept" = "${var.tags.Dept}"
    "Project-Code" = "${var.tags.Project-Code}"
    "Project-Desc" = "${var.tags.Project-Desc}"
    "Region" = "${var.tags.Region}"
    "Environment" = "${var.tags.Environment}"
    "Zone" = "${var.tags.Zone}"
    "Tier" = "${var.tags.Tier}"
    "Ops-EndDate" = "${var.tags.Ops-EndDate}"
  }
}

################################################################################
# The mandatory variable to be passed to the module.
# This is a standard across all the modules.
################################################################################
variable "tags" {
  type = object({
    Agency-Code = string
    Dept = string
    Project-Code = string
    Project-Desc = string
    Region = string
    Environment = string
    Zone = string
    Tier = string
    Ops-EndDate = string
  })

  description = <<EOF
    (Required)  Map of mandatory parameters that have to be passed to each layer-1 component. The value is an object with the following attributes:
    - Agency-Code: (Required) The Agency code.
    - Project-Code: (Required) The Project code.
    - Region: (Required) AWS Region.
    - Environment: (Required) Environment name.
    - Zone: (Required) The Zone where the resource will be created. Typical values are : ez|iz|mgmt
    - Tier: (Required) The Tier where the resource will be created. Typical values are : web|gut|app|it|db|vpcendpoint|mgmt

    ```
      eg: {
        "Agency-Code": "abc",
        "Dept": "def",
        "Project-Code": "xyz",
        "Region": "ap-southeast-1",
        "Environment": "dev",
        "Zone": "ez",
        "Tier": "web"
      }
    ```
  EOF

  # validate agency code must not be empty
  validation {
    condition     = length(var.tags.Agency-Code) > 0
    error_message = "The Agency-Code must not be empty."
  }

  # validate agency code must not be empty
  validation {
    condition     = length(var.tags.Dept) > 0
    error_message = "The Dept must not be empty."
  }

  # validate project code must not be empty
  validation {
    condition     = length(var.tags.Project-Code) > 0
    error_message = "The Project-Code must not be empty."
  }

  # validate Region must not be empty
  validation {
    condition     = length(var.tags.Region) > 0
    error_message = "The Region must not be empty."
  }

  # validate Environment must not be empty
  validation {
    condition     = length(var.tags.Environment) > 0
    error_message = "The Environment must not be empty."
  }
  
  # validate Zone must not be empty
  validation {
    condition     = length(var.tags.Zone) > 0
    error_message = "The Zone must not be empty."
  }

  # # validate Tier must not be empty
  # validation {
  #   condition     = length(var.tags.Tier) > 0
  #   error_message = "The Tier must not be empty."
  # }
}


variable "additional_tags" {
    type = map(string)
    default = {}
    description = <<EOT
    (Optional) These are the additional tags that are provided by the user. The values provided in the tags will *override* the tags generated by the module. 

    eg: 
    additional_tags : {
        "Name" ="my-name"
        "cost-center" = "my-cost-center"
    }

    The Name has the potential to override the Name formed by the module. 
    Ideally, the additional tags should be used to pass non standard tags eg cost-center, etc
    EOT
}