# # ###########################################################
# SES data file is not used by projects
# # ###########################################################

# locals {
#   domains = flatten(
#     [for domain in aws_ses_domain_identity.domain :
#       {
#         domain_short = split(".", domain.domain)[0]
#         domain_name  = domain.domain
#       }
#     ]
#   )
# }

# resource "local_file" "outputdata" {
#   filename        = "${path.module}/../data/data.${local.path}.tf"
#   file_permission = "0664"
#   content         = <<EOT
# ###########################################################
# # auto generated by project                               #
# # do not reference directly using id.                     #
# # you shall always reference with:                        #
# #  - $${local.xxx_prefix}                                  #
# #  - $${terraform.workspace}                               #
# #  - $${local.route53_zone_prefix}                         #
# ###########################################################
# %{for domain in local.domains~}
# data "aws_ses_domain_identity" "${domain.domain_short}" {
#   domain = "${domain.domain_name}"
# }

# %{endfor~}
#   EOT
# }

output "reminder" {
  value = <<EOT
    Remember to insert the DNS entry to validate the SES domain.
    You will need:
      1 TXT
      1 MX
      3 CNAME
    
    To setup _dmarc
    You will need:
      1 TXT
    
    In total:
      2 TXT
      1 MX
      3 CNAME
  EOT
}