###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
#  - ${local.route53_zone_prefix}                         #
###########################################################
data "aws_iam_role" "apigw-logger" {
  name = "${local.iam_role_prefix}-${terraform.workspace}-sharedinfra-apigw-logger"
}

data "aws_iam_role" "vpc-flow-logger" {
  name = "${local.iam_role_prefix}-${terraform.workspace}-sharedinfra-vpc-flow-logger"
}

data "aws_iam_role" "gitlab" {
  name = "${local.iam_role_prefix}-${terraform.workspace}-sharedinfra-gitlab"
}

data "aws_iam_role" "sns-delivery" {
  name = "${local.iam_role_prefix}-${terraform.workspace}-sharedinfra-sns-delivery"
}
