# resource "local_file" "outputdata" {
#   filename        = "${path.module}/../data/data.${local.path}.tf"
#   file_permission = "0664"
#   content         = <<-EOT
# ###########################################################
# # auto generated by project                               #
# # do not reference directly using id.                     #
# # you shall always reference with:                        #
# #  - $${local.xxx_prefix}                                  #
# #  - $${terraform.workspace}                               #
# ###########################################################
# data "aws_lambda_function" "slack_notification" {
#   function_name = "$${local.lambda_prefix}-$${terraform.workspace}${var.zone}${var.tier}-${var.project_code}${var.project_desc}"
# }

# data "aws_sns_topic" "slack_notification" {
#   name = "$${local.sns_prefix}-$${terraform.workspace}${var.zone}${var.tier}-${var.project_code}${var.project_desc}"
# }
#   EOT
# }