###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
#  - ${local.route53_zone_prefix}                         #
###########################################################
data "aws_vpc" "sharedsvc_ez" {
  filter {
    name   = "tag:Terraform"
    values = ["true"]
  }
  filter {
    name   = "tag:Environment"
    values = ["${terraform.workspace}"]
  }
  filter {
    name   = "tag:Project-Code"
    values = ["sharedsvc"]
  }
  filter {
    name   = "tag:Zone"
    values = ["ez"]
  }
}
