###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
#  - ${local.route53_zone_prefix}                         #
###########################################################
# USE AS ENVIRONMENT VARIABLE
locals {
  SHAREDSVC_ANALYTICS__BUCKET = "${data.aws_s3_bucket.analytics.id}"
  SHAREDSVC_EMAIL__BUCKET = "${data.aws_s3_bucket.email.id}"
  SHAREDSVC_SCHEDULER__BUCKET = "${data.aws_s3_bucket.scheduler.id}"
}

data "aws_s3_bucket" "analytics" {
  bucket = "${local.s3_prefix}-${terraform.workspace}ez-sharedsvc-${data.aws_caller_identity.current.account_id}-analytics"
}

data "aws_s3_bucket" "email" {
  bucket = "${local.s3_prefix}-${terraform.workspace}ez-sharedsvc-${data.aws_caller_identity.current.account_id}-email"
}

data "aws_s3_bucket" "scheduler" {
  bucket = "${local.s3_prefix}-${terraform.workspace}ez-sharedsvc-${data.aws_caller_identity.current.account_id}-scheduler"
}
