resource "local_file" "outputdata" {
  filename        = "${path.module}/../data/data.${local.path}.tf"
  file_permission = "0664"
  content         = <<-EOT
###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - $${local.xxx_prefix}                                  #
#  - $${terraform.workspace}                               #
#  - $${local.route53_zone_prefix}                         #
###########################################################
# USE AS ENVIRONMENT VARIABLE
%{for entry in var.pte_api~}
data "aws_lambda_function" "${entry.name}" {
  function_name = "$${local.lambda_prefix}-$${terraform.workspace}${var.zone}${var.tier}-${var.project_code}-${var.project_desc}-${entry.name}"
}

locals {
  ${upper( replace(var.project_code, "-", "_") )}_${upper( replace(entry.name, "-", "_") )}__PTE_URL = "https://${entry.host}$${local.PTE_URL}${entry.path_pattern[0]}"
}

%{endfor~}
  EOT
}

