###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
#  - ${local.route53_zone_prefix}                         #
###########################################################
data "aws_s3_bucket" "aibots_cloudfront" {
  bucket = "s3-${terraform.workspace}ezingress-aibots-${data.aws_caller_identity.current.account_id}-cloudfront"
}

data "aws_secretsmanager_secret" "aibots_cloudfront" {
  name = "${local.secret_prefix}-${terraform.workspace}ezingress-aibots-cloudfront"
}

data "aws_ssm_parameter" "aibots_cloudfront" {
  name = "${local.para_store_prefix}-${terraform.workspace}ezingress-aibots-cloudfront-publickey"
}

# USE AS ENVIRONMENT VARIABLE
locals {
  AIBOTS_CLOUDFRONT__PUB_URL = "https://public.${local.route53_zone_prefix}aibots.gov.sg"
  AIBOTS_CLOUDFRONT__BUCKET = "${data.aws_s3_bucket.aibots_cloudfront.id}"
  AIBOTS_CLOUDFRONT__SECRET = "${data.aws_secretsmanager_secret.aibots_cloudfront.name}"
  AIBOTS_CLOUDFRONT__PARAM = "${data.aws_ssm_parameter.aibots_cloudfront.name}"
}
