resource "local_file" "outputdata" {
  filename        = "${path.module}/../data/data.${local.path}.tf"
  file_permission = "0664"
  content         = <<-EOT
###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - $${local.xxx_prefix}                                  #
#  - $${terraform.workspace}                               #
###########################################################
locals {
  ${upper( replace(var.project_code, "-", "_") )}_${upper( replace(var.project_desc, "-", "_") )}__PUB_URL = "${lower(var.protocol)}://${var.pub.host == null ? "not_set" : var.pub.host}$${local.PUB_URL}"
  ${upper( replace(var.project_code, "-", "_") )}_${upper( replace(var.project_desc, "-", "_") )}__PTE_URL = "${lower(var.protocol)}://${var.pte.host == null ? "not_set" : var.pte.host}$${local.PTE_URL}"
  ${upper( replace(var.project_code, "-", "_") )}__${upper(local.secret_prefix)} = "$${data.aws_secretsmanager_secret.${var.project_code}-${var.project_desc}.name}"
  ${upper( replace(var.project_code, "-", "_") )}__PARAM = "$${data.aws_ssm_parameter.${var.project_code}-${var.project_desc}.name}"

}

data "aws_secretsmanager_secret" "${var.project_code}-${var.project_desc}" {
  name = "$${local.secret_prefix}-$${terraform.workspace}${var.zone}${var.tier}-${var.project_code}-${var.project_desc}"
}

data "aws_ssm_parameter" "${var.project_code}-${var.project_desc}" {
  name  = "$${local.para_store_prefix}-$${terraform.workspace}${var.zone}${var.tier}-${var.project_code}-${var.project_desc}"
}

# data "aws_ecr_repository" "${var.project_code}-${var.project_desc}" {
#   name = "$${local.ecr_prefix}-$${terraform.workspace}${var.zone}${var.tier}-${var.project_code}-${var.project_desc}"
# }
  EOT
}

output ecr_pte {
  value = var.pte.host == null ? "not_set" : "${aws_ecr_repository.project_pte[0].repository_url}"
}

output ecr_pub {
  value = var.pub.host == null ? "not_set" : "${aws_ecr_repository.project_pub[0].repository_url}"
}

output fqdn_pte {
  value = var.pte.host == null ? "not_set" : "${var.pte.host}$${local.PTE_URL}"
}

output fqdn_pub {
  value = var.pub.host == null ? "not_set" : "${var.pub.host}$${local.PUB_URL}"
}