output "reminder" {
  value = <<EOT
    Remember to configure the API gateway logging to use the IAM.

    Manaually generate the access key from console if need.
}
  EOT
}

resource "local_file" "outputdata" {
  filename        = "${path.module}/../data/data.${local.path}.tf"
  file_permission = "0664"
  content         = <<EOT
###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - $${local.xxx_prefix}                                  #
#  - $${terraform.workspace}                               #
#  - $${local.route53_zone_prefix}                         #
###########################################################
data "aws_iam_role" "apigw-logger" {
  name = "$${local.iam_role_prefix}-$${terraform.workspace}-${var.project_code}-apigw-logger"
}

data "aws_iam_role" "vpc-flow-logger" {
  name = "$${local.iam_role_prefix}-$${terraform.workspace}-${var.project_code}-vpc-flow-logger"
}

data "aws_iam_role" "gitlab" {
  name = "$${local.iam_role_prefix}-$${terraform.workspace}-${var.project_code}-gitlab"
}

data "aws_iam_role" "sns-delivery" {
  name = "$${local.iam_role_prefix}-$${terraform.workspace}-${var.project_code}-sns-delivery"
}
EOT
}