# output "reminder" {
#   value = <<EOT
#     Remember to configure the API gateway logging to use the IAM.
#   EOT
# }

resource "local_file" "outputdata" {
  filename        = "${path.module}/../data/data.${local.path}.tf"
  file_permission = "0664"
  content         = <<EOT
###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - $${local.xxx_prefix}                                  #
#  - $${terraform.workspace}                               #
#  - $${local.route53_zone_prefix}                         #
###########################################################

%{for entry in var.buckets~}
data "aws_s3_bucket" "${entry}" {
  bucket = "$${local.s3_prefix}-$${terraform.workspace}${var.zone}${var.tier}-${var.project_code}-$${data.aws_caller_identity.current.account_id}-${entry}"
}

%{endfor~}
EOT
}