###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
#  - ${local.route53_zone_prefix}                         #
###########################################################

# USE AS ENVIRONMENT VARIABLE
locals {
  AIBOTS_EMAIL_SMTP__SECRET = "${data.aws_secretsmanager_secret.aibots-smtp-user-no-reply.name}"
}

data "aws_secretsmanager_secret" "aibots-smtp-user-no-reply" {
  name = "${local.secret_prefix}-${terraform.workspace}ezapp-aibots-smtp-user-no-reply"
}

