###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
#  - ${local.route53_zone_prefix}                         #
###########################################################
# USE AS ENVIRONMENT VARIABLE
data "aws_lambda_function" "email-send" {
  function_name = "${local.lambda_prefix}-${terraform.workspace}ezapp-sharedsvc-api-email-send"
}

locals {
  SHAREDSVC_EMAIL_SEND__PTE_URL = "https://email.${local.PTE_URL}/send"
}

