###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - ${local.xxx_prefix}                                  #
#  - ${terraform.workspace}                               #
#  - ${local.route53_zone_prefix}                         #
###########################################################
################################################################################
# # nacl is different from subnets route_tables and security_groups
# # nacl does not have a data.aws_network_acl
# # it only has nacl.aws_network_acls (note the S) which only return a list of nacl_ids
# # the typical auto gen with vpc_id will not work.
################################################################################
data "aws_ssm_parameter" "aibots-cloak" {
  name  = "${local.para_store_prefix}-${terraform.workspace}ez-aibots-cloak"
}

data "aws_ssm_parameter" "aibots-llmstack" {
  name  = "${local.para_store_prefix}-${terraform.workspace}ez-aibots-llmstack"
}

# USE AS ENVIRONMENT VARIABLE
locals {
  AIBOTS_CLOAK__PARAM = "${data.aws_ssm_parameter.aibots-cloak.name}"
  AIBOTS_LLMSTACK__PARAM = "${data.aws_ssm_parameter.aibots-llmstack.name}"
}
