resource "local_file" "outputdata" {
  count = terraform.workspace == "sit" ? 1 : 0 # only deploy on SIT

  filename        = "${path.module}/../data/data.${local.path}.tf"
  file_permission = "0664"
  content         = <<-EOT
###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - $${local.xxx_prefix}                                  #
#  - $${terraform.workspace}                               #
#  - $${local.route53_zone_prefix}                         #
###########################################################
# lambda arn for:
# - cloudwatch logs subscription filter
# - SQS DLQ
data "aws_lambda_function" "notification" {
  function_name = "$${local.lambda_prefix}-$${terraform.workspace}${var.zone}${var.tier}-${var.project_code}-${var.project_desc}"
}

# SNS for:
# cloudwatch resource monitoring
data "aws_sns_topic" "notification" {
  name = "$${local.sns_prefix}-$${terraform.workspace}${var.zone}${var.tier}-${var.project_code}-${var.project_desc}"
}

  EOT
}
# put this back if you need to have this output
# # FQDN for:
# # workload notification
# locals {
#   notification_url = [%{for url in var.host_header_pte~} "${url}", %{endfor~}]
# }
