resource "local_file" "outputdata" {
  filename        = "${path.module}/../data/data.${local.path}.tf"
  file_permission = "0664"
  content         = <<EOT
###########################################################
# auto generated by project                               #
# do not reference directly using id.                     #
# you shall always reference with:                        #
#  - $${local.xxx_prefix}                                  #
#  - $${terraform.workspace}                               #
#  - $${local.route53_zone_prefix}                         #
###########################################################
data "aws_ec2_transit_gateway" "${var.project_code}_${var.zone}" {
  filter {
    name     = "tag:Terraform"
    values = ["true"]
  }
  filter {
    name     = "tag:Environment"
    values = ["$${terraform.workspace}"]
  }
  filter {
    name     = "tag:Project-Code"
    values = ["${var.project_code}"]
  }
  filter {
    name     = "tag:Zone"
    values = ["${var.zone}"]
  }
}
  EOT
}

output "reminder" {
  value = <<EOT
    When you are destroying, remember to remove the TAGS manually.
    Else you will have to wait till AWS remove the deleted TGW before you can correctly reference to it in other project.
  EOT
}